//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmberFlexberryDummy
{
    using System;
    using System.Xml;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// ApplicationBS.
    /// </summary>
    // *** Start programmer edit section *** (ApplicationBS CustomAttributes)

    // *** End programmer edit section *** (ApplicationBS CustomAttributes)
    [ICSSoft.STORMNET.AccessType(ICSSoft.STORMNET.AccessType.none)]
    public class ApplicationBS : ICSSoft.STORMNET.Business.BusinessServer
    {
        
        // *** Start programmer edit section *** (ApplicationBS CustomMembers)

        // *** End programmer edit section *** (ApplicationBS CustomMembers)

        
        // *** Start programmer edit section *** (OnUpdateApplicationUser CustomAttributes)

        // *** End programmer edit section *** (OnUpdateApplicationUser CustomAttributes)
        public virtual ICSSoft.STORMNET.DataObject[] OnUpdateApplicationUser(EmberFlexberryDummy.ApplicationUser UpdatedObject)
        {
            // *** Start programmer edit section *** (OnUpdateApplicationUser)

            return new ICSSoft.STORMNET.DataObject[0];
            // *** End programmer edit section *** (OnUpdateApplicationUser)
        }
        
        // *** Start programmer edit section *** (OnUpdateSuggestion CustomAttributes)

        // *** End programmer edit section *** (OnUpdateSuggestion CustomAttributes)
        public virtual ICSSoft.STORMNET.DataObject[] OnUpdateSuggestion(EmberFlexberryDummy.Suggestion UpdatedObject)
        {
            // *** Start programmer edit section *** (OnUpdateSuggestion)

            return new ICSSoft.STORMNET.DataObject[0];
            // *** End programmer edit section *** (OnUpdateSuggestion)
        }
        
        // *** Start programmer edit section *** (OnUpdateSuggestionType CustomAttributes)

        // *** End programmer edit section *** (OnUpdateSuggestionType CustomAttributes)
        public virtual ICSSoft.STORMNET.DataObject[] OnUpdateSuggestionType(EmberFlexberryDummy.SuggestionType UpdatedObject)
        {
            // *** Start programmer edit section *** (OnUpdateSuggestionType)

            return new ICSSoft.STORMNET.DataObject[0];
            // *** End programmer edit section *** (OnUpdateSuggestionType)
        }
    }
}
