//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmberFlexberryDummy
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// CatalogMaster.
    /// </summary>
    // *** Start programmer edit section *** (CatalogMaster CustomAttributes)

    // *** End programmer edit section *** (CatalogMaster CustomAttributes)
    [AutoAltered()]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("CatalogMasterE", new string[] {
            "name"})]
    [View("CatalogMasterL", new string[] {
            "name"})]
    public class CatalogMaster : ICSSoft.STORMNET.DataObject
    {
        
        private string fname;
        
        // *** Start programmer edit section *** (CatalogMaster CustomMembers)

        // *** End programmer edit section *** (CatalogMaster CustomMembers)

        
        /// <summary>
        /// name.
        /// </summary>
        // *** Start programmer edit section *** (CatalogMaster.name CustomAttributes)

        // *** End programmer edit section *** (CatalogMaster.name CustomAttributes)
        public virtual string name
        {
            get
            {
                // *** Start programmer edit section *** (CatalogMaster.name Get start)

                // *** End programmer edit section *** (CatalogMaster.name Get start)
                string result = this.fname;
                // *** Start programmer edit section *** (CatalogMaster.name Get end)

                // *** End programmer edit section *** (CatalogMaster.name Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (CatalogMaster.name Set start)

                // *** End programmer edit section *** (CatalogMaster.name Set start)
                this.fname = value;
                // *** Start programmer edit section *** (CatalogMaster.name Set end)

                // *** End programmer edit section *** (CatalogMaster.name Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// Справочник для проверки локализации.
            /// </summary>
            public static ICSSoft.STORMNET.View CatalogMasterE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("CatalogMasterE", typeof(EmberFlexberryDummy.CatalogMaster));
                }
            }
            
            /// <summary>
            /// Справочник для проверки локализации справочников.
            /// </summary>
            public static ICSSoft.STORMNET.View CatalogMasterL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("CatalogMasterL", typeof(EmberFlexberryDummy.CatalogMaster));
                }
            }
        }
    }
}
