//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmberFlexberryDummy
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Catalog.
    /// </summary>
    // *** Start programmer edit section *** (Catalog CustomAttributes)

    // *** End programmer edit section *** (Catalog CustomAttributes)
    [AutoAltered()]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("CatalogE", new string[] {
            "name as \'Name\'",
            "CatalogMaster as \'Catalog Master name\'",
            "CatalogMaster.name as \'Catalog Master name\'"}, Hidden=new string[] {
            "CatalogMaster.name"})]
    [AssociatedDetailViewAttribute("CatalogE", "listLocalization", "listLocalizationD", true, "", "listLocalization", true, new string[] {
            ""})]
    [MasterViewDefineAttribute("CatalogE", "CatalogMaster", ICSSoft.STORMNET.LookupTypeEnum.Standard, "", "")]
    [View("CatalogL", new string[] {
            "name as \'Name\'",
            "CatalogMaster.name as \'Catalog Master name\'"})]
    public class Catalog : ICSSoft.STORMNET.DataObject
    {
        
        private string fname;
        
        private EmberFlexberryDummy.CatalogMaster fCatalogMaster;
        
        private EmberFlexberryDummy.DetailArrayOflistLocalization flistLocalization;
        
        // *** Start programmer edit section *** (Catalog CustomMembers)

        // *** End programmer edit section *** (Catalog CustomMembers)

        
        /// <summary>
        /// name.
        /// </summary>
        // *** Start programmer edit section *** (Catalog.name CustomAttributes)

        // *** End programmer edit section *** (Catalog.name CustomAttributes)
        public virtual string name
        {
            get
            {
                // *** Start programmer edit section *** (Catalog.name Get start)

                // *** End programmer edit section *** (Catalog.name Get start)
                string result = this.fname;
                // *** Start programmer edit section *** (Catalog.name Get end)

                // *** End programmer edit section *** (Catalog.name Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Catalog.name Set start)

                // *** End programmer edit section *** (Catalog.name Set start)
                this.fname = value;
                // *** Start programmer edit section *** (Catalog.name Set end)

                // *** End programmer edit section *** (Catalog.name Set end)
            }
        }
        
        /// <summary>
        /// Catalog.
        /// </summary>
        // *** Start programmer edit section *** (Catalog.CatalogMaster CustomAttributes)

        // *** End programmer edit section *** (Catalog.CatalogMaster CustomAttributes)
        [PropertyStorage(new string[] {
                "CatalogMaster"})]
        [NotNull()]
        public virtual EmberFlexberryDummy.CatalogMaster CatalogMaster
        {
            get
            {
                // *** Start programmer edit section *** (Catalog.CatalogMaster Get start)

                // *** End programmer edit section *** (Catalog.CatalogMaster Get start)
                EmberFlexberryDummy.CatalogMaster result = this.fCatalogMaster;
                // *** Start programmer edit section *** (Catalog.CatalogMaster Get end)

                // *** End programmer edit section *** (Catalog.CatalogMaster Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Catalog.CatalogMaster Set start)

                // *** End programmer edit section *** (Catalog.CatalogMaster Set start)
                this.fCatalogMaster = value;
                // *** Start programmer edit section *** (Catalog.CatalogMaster Set end)

                // *** End programmer edit section *** (Catalog.CatalogMaster Set end)
            }
        }
        
        /// <summary>
        /// Catalog.
        /// </summary>
        // *** Start programmer edit section *** (Catalog.listLocalization CustomAttributes)

        // *** End programmer edit section *** (Catalog.listLocalization CustomAttributes)
        public virtual EmberFlexberryDummy.DetailArrayOflistLocalization listLocalization
        {
            get
            {
                // *** Start programmer edit section *** (Catalog.listLocalization Get start)

                // *** End programmer edit section *** (Catalog.listLocalization Get start)
                if ((this.flistLocalization == null))
                {
                    this.flistLocalization = new EmberFlexberryDummy.DetailArrayOflistLocalization(this);
                }
                EmberFlexberryDummy.DetailArrayOflistLocalization result = this.flistLocalization;
                // *** Start programmer edit section *** (Catalog.listLocalization Get end)

                // *** End programmer edit section *** (Catalog.listLocalization Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Catalog.listLocalization Set start)

                // *** End programmer edit section *** (Catalog.listLocalization Set start)
                this.flistLocalization = value;
                // *** Start programmer edit section *** (Catalog.listLocalization Set end)

                // *** End programmer edit section *** (Catalog.listLocalization Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// Представление для проверки локализации справочников.
            /// </summary>
            public static ICSSoft.STORMNET.View CatalogE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("CatalogE", typeof(EmberFlexberryDummy.Catalog));
                }
            }
            
            /// <summary>
            /// Представление для проверки локализации справочников.
            /// </summary>
            public static ICSSoft.STORMNET.View CatalogL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("CatalogL", typeof(EmberFlexberryDummy.Catalog));
                }
            }
        }
    }
}
