//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmberFlexberryDummy
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// ChildLevel2.
    /// </summary>
    // *** Start programmer edit section *** (ChildLevel2 CustomAttributes)

    // *** End programmer edit section *** (ChildLevel2 CustomAttributes)
    [AutoAltered()]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("AllProps2", new string[] {
            "Author.*",
            "Type.*",
            "Type.Parent.*",
            "Type.Parent.Parent.*",
            "Editor1.*"}, Hidden=new string[] {
            "Author.*"})]
    public class ChildLevel2 : EmberFlexberryDummy.ChildLevel1
    {
        
        private string fTextChild2;
        
        private EmberFlexberryDummyPost.EObj fobj;
        
        // *** Start programmer edit section *** (ChildLevel2 CustomMembers)

        // *** End programmer edit section *** (ChildLevel2 CustomMembers)

        
        /// <summary>
        /// TextChild2.
        /// </summary>
        // *** Start programmer edit section *** (ChildLevel2.TextChild2 CustomAttributes)

        // *** End programmer edit section *** (ChildLevel2.TextChild2 CustomAttributes)
        public virtual string TextChild2
        {
            get
            {
                // *** Start programmer edit section *** (ChildLevel2.TextChild2 Get start)

                // *** End programmer edit section *** (ChildLevel2.TextChild2 Get start)
                string result = this.fTextChild2;
                // *** Start programmer edit section *** (ChildLevel2.TextChild2 Get end)

                // *** End programmer edit section *** (ChildLevel2.TextChild2 Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ChildLevel2.TextChild2 Set start)

                // *** End programmer edit section *** (ChildLevel2.TextChild2 Set start)
                this.fTextChild2 = value;
                // *** Start programmer edit section *** (ChildLevel2.TextChild2 Set end)

                // *** End programmer edit section *** (ChildLevel2.TextChild2 Set end)
            }
        }
        
        /// <summary>
        /// obj.
        /// </summary>
        // *** Start programmer edit section *** (ChildLevel2.obj CustomAttributes)

        // *** End programmer edit section *** (ChildLevel2.obj CustomAttributes)
        public virtual EmberFlexberryDummyPost.EObj obj
        {
            get
            {
                // *** Start programmer edit section *** (ChildLevel2.obj Get start)

                // *** End programmer edit section *** (ChildLevel2.obj Get start)
                EmberFlexberryDummyPost.EObj result = this.fobj;
                // *** Start programmer edit section *** (ChildLevel2.obj Get end)

                // *** End programmer edit section *** (ChildLevel2.obj Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ChildLevel2.obj Set start)

                // *** End programmer edit section *** (ChildLevel2.obj Set start)
                this.fobj = value;
                // *** Start programmer edit section *** (ChildLevel2.obj Set end)

                // *** End programmer edit section *** (ChildLevel2.obj Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "AllProps2" view.
            /// </summary>
            public static ICSSoft.STORMNET.View AllProps2
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("AllProps2", typeof(EmberFlexberryDummy.ChildLevel2));
                }
            }
        }
    }
}
