//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmberFlexberryDummy
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// ChildLevel1.
    /// </summary>
    // *** Start programmer edit section *** (ChildLevel1 CustomAttributes)

    // *** End programmer edit section *** (ChildLevel1 CustomAttributes)
    [AutoAltered()]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("AllProps", new string[] {
            "*"}, Hidden=new string[] {
            "*"})]
    public class ChildLevel1 : EmberFlexberryDummy.Suggestion, EmberFlexberryDummy.Inter
    {
        
        private string fTextChild1;
        
        // *** Start programmer edit section *** (ChildLevel1 CustomMembers)

        // *** End programmer edit section *** (ChildLevel1 CustomMembers)

        
        /// <summary>
        /// TextChild1.
        /// </summary>
        // *** Start programmer edit section *** (ChildLevel1.TextChild1 CustomAttributes)

        // *** End programmer edit section *** (ChildLevel1.TextChild1 CustomAttributes)
        public virtual string TextChild1
        {
            get
            {
                // *** Start programmer edit section *** (ChildLevel1.TextChild1 Get start)

                // *** End programmer edit section *** (ChildLevel1.TextChild1 Get start)
                string result = this.fTextChild1;
                // *** Start programmer edit section *** (ChildLevel1.TextChild1 Get end)

                // *** End programmer edit section *** (ChildLevel1.TextChild1 Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ChildLevel1.TextChild1 Set start)

                // *** End programmer edit section *** (ChildLevel1.TextChild1 Set start)
                this.fTextChild1 = value;
                // *** Start programmer edit section *** (ChildLevel1.TextChild1 Set end)

                // *** End programmer edit section *** (ChildLevel1.TextChild1 Set end)
            }
        }
        
        /// <summary>
        /// TextIf.
        /// </summary>
        // *** Start programmer edit section *** (TextIf CustomAttributes)

        // *** End programmer edit section *** (TextIf CustomAttributes)
        [ICSSoft.STORMNET.NotStored()]
        public virtual string TextIf
        {
            get
            {
                // *** Start programmer edit section *** (TextIf Get)

                return null;
                // *** End programmer edit section *** (TextIf Get)
            }
            set
            {
                // *** Start programmer edit section *** (TextIf Set)

                // *** End programmer edit section *** (TextIf Set)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "AllProps" view.
            /// </summary>
            public static ICSSoft.STORMNET.View AllProps
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("AllProps", typeof(EmberFlexberryDummy.ChildLevel1));
                }
            }
        }
    }
}
