//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmberFlexberryDummy
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    using ICSSoft.STORMNET.Business.Audit;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Comment.
    /// </summary>
    // *** Start programmer edit section *** (Comment CustomAttributes)

    // *** End programmer edit section *** (Comment CustomAttributes)
    [AutoAltered()]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("AuditView", new string[] {
            "Text as \'Text\'",
            "Votes as \'Votes\'",
            "Moderated as \'Moderated\'",
            "Author as \'Author\'",
            "Author.Name as \'Name\'"}, Hidden=new string[] {
            "Author.Name"})]
    [AssociatedDetailViewAttribute("AuditView", "UserVotes", "AuditView", true, "", "User votes", true, new string[] {
            ""})]
    [MasterViewDefineAttribute("AuditView", "Author", ICSSoft.STORMNET.LookupTypeEnum.Standard, "", "Name")]
    [View("CommentD", new string[] {
            "Suggestion",
            "Text as \'Text\'",
            "Votes as \'Votes\'",
            "Moderated as \'Moderated\'",
            "Author as \'Author\'",
            "Author.Name as \'Name\'"}, Hidden=new string[] {
            "Suggestion",
            "Author.Name"})]
    [MasterViewDefineAttribute("CommentD", "Author", ICSSoft.STORMNET.LookupTypeEnum.Standard, "", "Name")]
    [View("CommentE", new string[] {
            "Suggestion as \'Address\'",
            "Suggestion.Address",
            "Text as \'Text\'",
            "Votes as \'Votes\'",
            "Moderated as \'Moderated\'",
            "Author as \'Author\'",
            "Author.Name as \'Name\'",
            "Author.Phone1 as \'Phone 1\'"}, Hidden=new string[] {
            "Suggestion",
            "Suggestion.Address",
            "Author.Name",
            "Author.Phone1"})]
    [AssociatedDetailViewAttribute("CommentE", "UserVotes", "CommentVoteE", true, "", "User votes", true, new string[] {
            ""})]
    [MasterViewDefineAttribute("CommentE", "Author", ICSSoft.STORMNET.LookupTypeEnum.Standard, "", "Name")]
    public class Comment : ICSSoft.STORMNET.DataObject, IDataObjectWithAuditFields
    {
        
        private System.Nullable<System.DateTime> fCreateTime;
        
        private string fCreator;
        
        private System.Nullable<System.DateTime> fEditTime;
        
        private string fEditor;
        
        private string fText;
        
        private long fVotes;
        
        private bool fModerated;
        
        private EmberFlexberryDummy.ApplicationUser fAuthor;
        
        private EmberFlexberryDummy.DetailArrayOfCommentVote fUserVotes;
        
        private EmberFlexberryDummy.Suggestion fSuggestion;
        
        // *** Start programmer edit section *** (Comment CustomMembers)

        // *** End programmer edit section *** (Comment CustomMembers)

        
        /// <summary>
        /// Время создания объекта.
        /// </summary>
        // *** Start programmer edit section *** (Comment.CreateTime CustomAttributes)

        // *** End programmer edit section *** (Comment.CreateTime CustomAttributes)
        public virtual System.Nullable<System.DateTime> CreateTime
        {
            get
            {
                // *** Start programmer edit section *** (Comment.CreateTime Get start)

                // *** End programmer edit section *** (Comment.CreateTime Get start)
                System.Nullable<System.DateTime> result = this.fCreateTime;
                // *** Start programmer edit section *** (Comment.CreateTime Get end)

                // *** End programmer edit section *** (Comment.CreateTime Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Comment.CreateTime Set start)

                // *** End programmer edit section *** (Comment.CreateTime Set start)
                this.fCreateTime = value;
                // *** Start programmer edit section *** (Comment.CreateTime Set end)

                // *** End programmer edit section *** (Comment.CreateTime Set end)
            }
        }
        
        /// <summary>
        /// Создатель объекта.
        /// </summary>
        // *** Start programmer edit section *** (Comment.Creator CustomAttributes)

        // *** End programmer edit section *** (Comment.Creator CustomAttributes)
        public virtual string Creator
        {
            get
            {
                // *** Start programmer edit section *** (Comment.Creator Get start)

                // *** End programmer edit section *** (Comment.Creator Get start)
                string result = this.fCreator;
                // *** Start programmer edit section *** (Comment.Creator Get end)

                // *** End programmer edit section *** (Comment.Creator Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Comment.Creator Set start)

                // *** End programmer edit section *** (Comment.Creator Set start)
                this.fCreator = value;
                // *** Start programmer edit section *** (Comment.Creator Set end)

                // *** End programmer edit section *** (Comment.Creator Set end)
            }
        }
        
        /// <summary>
        /// Время последнего редактирования объекта.
        /// </summary>
        // *** Start programmer edit section *** (Comment.EditTime CustomAttributes)

        // *** End programmer edit section *** (Comment.EditTime CustomAttributes)
        public virtual System.Nullable<System.DateTime> EditTime
        {
            get
            {
                // *** Start programmer edit section *** (Comment.EditTime Get start)

                // *** End programmer edit section *** (Comment.EditTime Get start)
                System.Nullable<System.DateTime> result = this.fEditTime;
                // *** Start programmer edit section *** (Comment.EditTime Get end)

                // *** End programmer edit section *** (Comment.EditTime Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Comment.EditTime Set start)

                // *** End programmer edit section *** (Comment.EditTime Set start)
                this.fEditTime = value;
                // *** Start programmer edit section *** (Comment.EditTime Set end)

                // *** End programmer edit section *** (Comment.EditTime Set end)
            }
        }
        
        /// <summary>
        /// Последний редактор объекта.
        /// </summary>
        // *** Start programmer edit section *** (Comment.Editor CustomAttributes)

        // *** End programmer edit section *** (Comment.Editor CustomAttributes)
        public virtual string Editor
        {
            get
            {
                // *** Start programmer edit section *** (Comment.Editor Get start)

                // *** End programmer edit section *** (Comment.Editor Get start)
                string result = this.fEditor;
                // *** Start programmer edit section *** (Comment.Editor Get end)

                // *** End programmer edit section *** (Comment.Editor Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Comment.Editor Set start)

                // *** End programmer edit section *** (Comment.Editor Set start)
                this.fEditor = value;
                // *** Start programmer edit section *** (Comment.Editor Set end)

                // *** End programmer edit section *** (Comment.Editor Set end)
            }
        }
        
        /// <summary>
        /// Text.
        /// </summary>
        // *** Start programmer edit section *** (Comment.Text CustomAttributes)

        // *** End programmer edit section *** (Comment.Text CustomAttributes)
        public virtual string Text
        {
            get
            {
                // *** Start programmer edit section *** (Comment.Text Get start)

                // *** End programmer edit section *** (Comment.Text Get start)
                string result = this.fText;
                // *** Start programmer edit section *** (Comment.Text Get end)

                // *** End programmer edit section *** (Comment.Text Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Comment.Text Set start)

                // *** End programmer edit section *** (Comment.Text Set start)
                this.fText = value;
                // *** Start programmer edit section *** (Comment.Text Set end)

                // *** End programmer edit section *** (Comment.Text Set end)
            }
        }
        
        /// <summary>
        /// Votes.
        /// </summary>
        // *** Start programmer edit section *** (Comment.Votes CustomAttributes)

        // *** End programmer edit section *** (Comment.Votes CustomAttributes)
        public virtual long Votes
        {
            get
            {
                // *** Start programmer edit section *** (Comment.Votes Get start)

                // *** End programmer edit section *** (Comment.Votes Get start)
                long result = this.fVotes;
                // *** Start programmer edit section *** (Comment.Votes Get end)

                // *** End programmer edit section *** (Comment.Votes Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Comment.Votes Set start)

                // *** End programmer edit section *** (Comment.Votes Set start)
                this.fVotes = value;
                // *** Start programmer edit section *** (Comment.Votes Set end)

                // *** End programmer edit section *** (Comment.Votes Set end)
            }
        }
        
        /// <summary>
        /// Moderated.
        /// </summary>
        // *** Start programmer edit section *** (Comment.Moderated CustomAttributes)

        // *** End programmer edit section *** (Comment.Moderated CustomAttributes)
        public virtual bool Moderated
        {
            get
            {
                // *** Start programmer edit section *** (Comment.Moderated Get start)

                // *** End programmer edit section *** (Comment.Moderated Get start)
                bool result = this.fModerated;
                // *** Start programmer edit section *** (Comment.Moderated Get end)

                // *** End programmer edit section *** (Comment.Moderated Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Comment.Moderated Set start)

                // *** End programmer edit section *** (Comment.Moderated Set start)
                this.fModerated = value;
                // *** Start programmer edit section *** (Comment.Moderated Set end)

                // *** End programmer edit section *** (Comment.Moderated Set end)
            }
        }
        
        /// <summary>
        /// Comment.
        /// </summary>
        // *** Start programmer edit section *** (Comment.Author CustomAttributes)

        // *** End programmer edit section *** (Comment.Author CustomAttributes)
        [PropertyStorage(new string[] {
                "Author"})]
        [NotNull()]
        public virtual EmberFlexberryDummy.ApplicationUser Author
        {
            get
            {
                // *** Start programmer edit section *** (Comment.Author Get start)

                // *** End programmer edit section *** (Comment.Author Get start)
                EmberFlexberryDummy.ApplicationUser result = this.fAuthor;
                // *** Start programmer edit section *** (Comment.Author Get end)

                // *** End programmer edit section *** (Comment.Author Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Comment.Author Set start)

                // *** End programmer edit section *** (Comment.Author Set start)
                this.fAuthor = value;
                // *** Start programmer edit section *** (Comment.Author Set end)

                // *** End programmer edit section *** (Comment.Author Set end)
            }
        }
        
        /// <summary>
        /// Comment.
        /// </summary>
        // *** Start programmer edit section *** (Comment.UserVotes CustomAttributes)

        // *** End programmer edit section *** (Comment.UserVotes CustomAttributes)
        public virtual EmberFlexberryDummy.DetailArrayOfCommentVote UserVotes
        {
            get
            {
                // *** Start programmer edit section *** (Comment.UserVotes Get start)

                // *** End programmer edit section *** (Comment.UserVotes Get start)
                if ((this.fUserVotes == null))
                {
                    this.fUserVotes = new EmberFlexberryDummy.DetailArrayOfCommentVote(this);
                }
                EmberFlexberryDummy.DetailArrayOfCommentVote result = this.fUserVotes;
                // *** Start programmer edit section *** (Comment.UserVotes Get end)

                // *** End programmer edit section *** (Comment.UserVotes Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Comment.UserVotes Set start)

                // *** End programmer edit section *** (Comment.UserVotes Set start)
                this.fUserVotes = value;
                // *** Start programmer edit section *** (Comment.UserVotes Set end)

                // *** End programmer edit section *** (Comment.UserVotes Set end)
            }
        }
        
        /// <summary>
        /// мастеровая ссылка на шапку EmberFlexberryDummy.Suggestion.
        /// </summary>
        // *** Start programmer edit section *** (Comment.Suggestion CustomAttributes)

        // *** End programmer edit section *** (Comment.Suggestion CustomAttributes)
        [Agregator()]
        [NotNull()]
        [PropertyStorage(new string[] {
                "Suggestion"})]
        [TypeUsage(new string[] {
                "EmberFlexberryDummy.Suggestion"})]
        public virtual EmberFlexberryDummy.Suggestion Suggestion
        {
            get
            {
                // *** Start programmer edit section *** (Comment.Suggestion Get start)

                // *** End programmer edit section *** (Comment.Suggestion Get start)
                EmberFlexberryDummy.Suggestion result = this.fSuggestion;
                // *** Start programmer edit section *** (Comment.Suggestion Get end)

                // *** End programmer edit section *** (Comment.Suggestion Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Comment.Suggestion Set start)

                // *** End programmer edit section *** (Comment.Suggestion Set start)
                this.fSuggestion = value;
                // *** Start programmer edit section *** (Comment.Suggestion Set end)

                // *** End programmer edit section *** (Comment.Suggestion Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "AuditView" view.
            /// </summary>
            public static ICSSoft.STORMNET.View AuditView
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("AuditView", typeof(EmberFlexberryDummy.Comment));
                }
            }
            
            /// <summary>
            /// "CommentD" view.
            /// </summary>
            public static ICSSoft.STORMNET.View CommentD
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("CommentD", typeof(EmberFlexberryDummy.Comment));
                }
            }
            
            /// <summary>
            /// "CommentE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View CommentE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("CommentE", typeof(EmberFlexberryDummy.Comment));
                }
            }
        }
    }
    
    /// <summary>
    /// Detail array of Comment.
    /// </summary>
    // *** Start programmer edit section *** (DetailArrayDetailArrayOfComment CustomAttributes)

    // *** End programmer edit section *** (DetailArrayDetailArrayOfComment CustomAttributes)
    public class DetailArrayOfComment : ICSSoft.STORMNET.DetailArray
    {
        
        // *** Start programmer edit section *** (EmberFlexberryDummy.DetailArrayOfComment members)

        // *** End programmer edit section *** (EmberFlexberryDummy.DetailArrayOfComment members)

        
        /// <summary>
        /// Construct detail array.
        /// </summary>
        /// <summary>
        /// Returns object with type Comment by index.
        /// </summary>
        /// <summary>
        /// Adds object with type Comment.
        /// </summary>
        public DetailArrayOfComment(EmberFlexberryDummy.Suggestion fSuggestion) : 
                base(typeof(Comment), ((ICSSoft.STORMNET.DataObject)(fSuggestion)))
        {
        }
        
        public EmberFlexberryDummy.Comment this[int index]
        {
            get
            {
                return ((EmberFlexberryDummy.Comment)(this.ItemByIndex(index)));
            }
        }
        
        public virtual void Add(EmberFlexberryDummy.Comment dataobject)
        {
            this.AddObject(((ICSSoft.STORMNET.DataObject)(dataobject)));
        }
    }
}
