//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmberFlexberryDummy
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    using ICSSoft.STORMNET.Business.Audit;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Comment vote.
    /// </summary>
    // *** Start programmer edit section *** (CommentVote CustomAttributes)

    // *** End programmer edit section *** (CommentVote CustomAttributes)
    [AutoAltered()]
    [Caption("Comment vote")]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("AuditView", new string[] {
            "VoteType as \'Vote type\'",
            "ApplicationUser as \'Application user\'",
            "ApplicationUser.Name as \'Name\'"}, Hidden=new string[] {
            "ApplicationUser.Name"})]
    [MasterViewDefineAttribute("AuditView", "ApplicationUser", ICSSoft.STORMNET.LookupTypeEnum.Standard, "", "Name")]
    [View("CommentVoteE", new string[] {
            "VoteType as \'Vote type\'",
            "ApplicationUser as \'Application user\'",
            "ApplicationUser.Name as \'Name\'",
            "Comment"}, Hidden=new string[] {
            "ApplicationUser.Name",
            "Comment"})]
    [MasterViewDefineAttribute("CommentVoteE", "ApplicationUser", ICSSoft.STORMNET.LookupTypeEnum.Standard, "", "Name")]
    public class CommentVote : ICSSoft.STORMNET.DataObject, IDataObjectWithAuditFields
    {
        
        private System.Nullable<System.DateTime> fCreateTime;
        
        private string fCreator;
        
        private System.Nullable<System.DateTime> fEditTime;
        
        private string fEditor;
        
        private EmberFlexberryDummy.VoteType fVoteType;
        
        private EmberFlexberryDummy.ApplicationUser fApplicationUser;
        
        private EmberFlexberryDummy.Comment fComment;
        
        // *** Start programmer edit section *** (CommentVote CustomMembers)

        // *** End programmer edit section *** (CommentVote CustomMembers)

        
        /// <summary>
        /// Время создания объекта.
        /// </summary>
        // *** Start programmer edit section *** (CommentVote.CreateTime CustomAttributes)

        // *** End programmer edit section *** (CommentVote.CreateTime CustomAttributes)
        public virtual System.Nullable<System.DateTime> CreateTime
        {
            get
            {
                // *** Start programmer edit section *** (CommentVote.CreateTime Get start)

                // *** End programmer edit section *** (CommentVote.CreateTime Get start)
                System.Nullable<System.DateTime> result = this.fCreateTime;
                // *** Start programmer edit section *** (CommentVote.CreateTime Get end)

                // *** End programmer edit section *** (CommentVote.CreateTime Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (CommentVote.CreateTime Set start)

                // *** End programmer edit section *** (CommentVote.CreateTime Set start)
                this.fCreateTime = value;
                // *** Start programmer edit section *** (CommentVote.CreateTime Set end)

                // *** End programmer edit section *** (CommentVote.CreateTime Set end)
            }
        }
        
        /// <summary>
        /// Создатель объекта.
        /// </summary>
        // *** Start programmer edit section *** (CommentVote.Creator CustomAttributes)

        // *** End programmer edit section *** (CommentVote.Creator CustomAttributes)
        public virtual string Creator
        {
            get
            {
                // *** Start programmer edit section *** (CommentVote.Creator Get start)

                // *** End programmer edit section *** (CommentVote.Creator Get start)
                string result = this.fCreator;
                // *** Start programmer edit section *** (CommentVote.Creator Get end)

                // *** End programmer edit section *** (CommentVote.Creator Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (CommentVote.Creator Set start)

                // *** End programmer edit section *** (CommentVote.Creator Set start)
                this.fCreator = value;
                // *** Start programmer edit section *** (CommentVote.Creator Set end)

                // *** End programmer edit section *** (CommentVote.Creator Set end)
            }
        }
        
        /// <summary>
        /// Время последнего редактирования объекта.
        /// </summary>
        // *** Start programmer edit section *** (CommentVote.EditTime CustomAttributes)

        // *** End programmer edit section *** (CommentVote.EditTime CustomAttributes)
        public virtual System.Nullable<System.DateTime> EditTime
        {
            get
            {
                // *** Start programmer edit section *** (CommentVote.EditTime Get start)

                // *** End programmer edit section *** (CommentVote.EditTime Get start)
                System.Nullable<System.DateTime> result = this.fEditTime;
                // *** Start programmer edit section *** (CommentVote.EditTime Get end)

                // *** End programmer edit section *** (CommentVote.EditTime Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (CommentVote.EditTime Set start)

                // *** End programmer edit section *** (CommentVote.EditTime Set start)
                this.fEditTime = value;
                // *** Start programmer edit section *** (CommentVote.EditTime Set end)

                // *** End programmer edit section *** (CommentVote.EditTime Set end)
            }
        }
        
        /// <summary>
        /// Последний редактор объекта.
        /// </summary>
        // *** Start programmer edit section *** (CommentVote.Editor CustomAttributes)

        // *** End programmer edit section *** (CommentVote.Editor CustomAttributes)
        public virtual string Editor
        {
            get
            {
                // *** Start programmer edit section *** (CommentVote.Editor Get start)

                // *** End programmer edit section *** (CommentVote.Editor Get start)
                string result = this.fEditor;
                // *** Start programmer edit section *** (CommentVote.Editor Get end)

                // *** End programmer edit section *** (CommentVote.Editor Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (CommentVote.Editor Set start)

                // *** End programmer edit section *** (CommentVote.Editor Set start)
                this.fEditor = value;
                // *** Start programmer edit section *** (CommentVote.Editor Set end)

                // *** End programmer edit section *** (CommentVote.Editor Set end)
            }
        }
        
        /// <summary>
        /// VoteType.
        /// </summary>
        // *** Start programmer edit section *** (CommentVote.VoteType CustomAttributes)

        // *** End programmer edit section *** (CommentVote.VoteType CustomAttributes)
        public virtual EmberFlexberryDummy.VoteType VoteType
        {
            get
            {
                // *** Start programmer edit section *** (CommentVote.VoteType Get start)

                // *** End programmer edit section *** (CommentVote.VoteType Get start)
                EmberFlexberryDummy.VoteType result = this.fVoteType;
                // *** Start programmer edit section *** (CommentVote.VoteType Get end)

                // *** End programmer edit section *** (CommentVote.VoteType Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (CommentVote.VoteType Set start)

                // *** End programmer edit section *** (CommentVote.VoteType Set start)
                this.fVoteType = value;
                // *** Start programmer edit section *** (CommentVote.VoteType Set end)

                // *** End programmer edit section *** (CommentVote.VoteType Set end)
            }
        }
        
        /// <summary>
        /// Comment vote.
        /// </summary>
        // *** Start programmer edit section *** (CommentVote.ApplicationUser CustomAttributes)

        // *** End programmer edit section *** (CommentVote.ApplicationUser CustomAttributes)
        [PropertyStorage(new string[] {
                "ApplicationUser"})]
        [NotNull()]
        public virtual EmberFlexberryDummy.ApplicationUser ApplicationUser
        {
            get
            {
                // *** Start programmer edit section *** (CommentVote.ApplicationUser Get start)

                // *** End programmer edit section *** (CommentVote.ApplicationUser Get start)
                EmberFlexberryDummy.ApplicationUser result = this.fApplicationUser;
                // *** Start programmer edit section *** (CommentVote.ApplicationUser Get end)

                // *** End programmer edit section *** (CommentVote.ApplicationUser Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (CommentVote.ApplicationUser Set start)

                // *** End programmer edit section *** (CommentVote.ApplicationUser Set start)
                this.fApplicationUser = value;
                // *** Start programmer edit section *** (CommentVote.ApplicationUser Set end)

                // *** End programmer edit section *** (CommentVote.ApplicationUser Set end)
            }
        }
        
        /// <summary>
        /// мастеровая ссылка на шапку EmberFlexberryDummy.Comment.
        /// </summary>
        // *** Start programmer edit section *** (CommentVote.Comment CustomAttributes)

        // *** End programmer edit section *** (CommentVote.Comment CustomAttributes)
        [Agregator()]
        [NotNull()]
        [PropertyStorage(new string[] {
                "Comment"})]
        public virtual EmberFlexberryDummy.Comment Comment
        {
            get
            {
                // *** Start programmer edit section *** (CommentVote.Comment Get start)

                // *** End programmer edit section *** (CommentVote.Comment Get start)
                EmberFlexberryDummy.Comment result = this.fComment;
                // *** Start programmer edit section *** (CommentVote.Comment Get end)

                // *** End programmer edit section *** (CommentVote.Comment Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (CommentVote.Comment Set start)

                // *** End programmer edit section *** (CommentVote.Comment Set start)
                this.fComment = value;
                // *** Start programmer edit section *** (CommentVote.Comment Set end)

                // *** End programmer edit section *** (CommentVote.Comment Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "AuditView" view.
            /// </summary>
            public static ICSSoft.STORMNET.View AuditView
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("AuditView", typeof(EmberFlexberryDummy.CommentVote));
                }
            }
            
            /// <summary>
            /// "CommentVoteE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View CommentVoteE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("CommentVoteE", typeof(EmberFlexberryDummy.CommentVote));
                }
            }
        }
    }
    
    /// <summary>
    /// Detail array of CommentVote.
    /// </summary>
    // *** Start programmer edit section *** (DetailArrayDetailArrayOfCommentVote CustomAttributes)

    // *** End programmer edit section *** (DetailArrayDetailArrayOfCommentVote CustomAttributes)
    public class DetailArrayOfCommentVote : ICSSoft.STORMNET.DetailArray
    {
        
        // *** Start programmer edit section *** (EmberFlexberryDummy.DetailArrayOfCommentVote members)

        // *** End programmer edit section *** (EmberFlexberryDummy.DetailArrayOfCommentVote members)

        
        /// <summary>
        /// Construct detail array.
        /// </summary>
        /// <summary>
        /// Returns object with type CommentVote by index.
        /// </summary>
        /// <summary>
        /// Adds object with type CommentVote.
        /// </summary>
        public DetailArrayOfCommentVote(EmberFlexberryDummy.Comment fComment) : 
                base(typeof(CommentVote), ((ICSSoft.STORMNET.DataObject)(fComment)))
        {
        }
        
        public EmberFlexberryDummy.CommentVote this[int index]
        {
            get
            {
                return ((EmberFlexberryDummy.CommentVote)(this.ItemByIndex(index)));
            }
        }
        
        public virtual void Add(EmberFlexberryDummy.CommentVote dataobject)
        {
            this.AddObject(((ICSSoft.STORMNET.DataObject)(dataobject)));
        }
    }
}
