//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmberFlexberryDummy
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Departament.
    /// </summary>
    // *** Start programmer edit section *** (Departament CustomAttributes)

    // *** End programmer edit section *** (Departament CustomAttributes)
    [AutoAltered()]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("DepartamentE", new string[] {
            "Name as \'Название\'",
            "Vid as \'Вид\'"})]
    [MasterViewDefineAttribute("DepartamentE", "vid", ICSSoft.STORMNET.LookupTypeEnum.Standard, "", "name")]
    [View("DepartamentL", new string[] {
            "Name as \'Название\'"})]
    public class Departament : ICSSoft.STORMNET.DataObject
    {
        
        private string fName;
        
        private EmberFlexberryDummy.VidDepartamenta fVid;
        
        // *** Start programmer edit section *** (Departament CustomMembers)

        // *** End programmer edit section *** (Departament CustomMembers)

        
        /// <summary>
        /// Name.
        /// </summary>
        // *** Start programmer edit section *** (Departament.Name CustomAttributes)

        // *** End programmer edit section *** (Departament.Name CustomAttributes)
        public virtual string Name
        {
            get
            {
                // *** Start programmer edit section *** (Departament.Name Get start)

                // *** End programmer edit section *** (Departament.Name Get start)
                string result = this.fName;
                // *** Start programmer edit section *** (Departament.Name Get end)

                // *** End programmer edit section *** (Departament.Name Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Departament.Name Set start)

                // *** End programmer edit section *** (Departament.Name Set start)
                this.fName = value;
                // *** Start programmer edit section *** (Departament.Name Set end)

                // *** End programmer edit section *** (Departament.Name Set end)
            }
        }
        
        /// <summary>
        /// Departament.
        /// </summary>
        // *** Start programmer edit section *** (Departament.Vid CustomAttributes)

        // *** End programmer edit section *** (Departament.Vid CustomAttributes)
        [PropertyStorage(new string[] {
                "Vid"})]
        [NotNull()]
        public virtual EmberFlexberryDummy.VidDepartamenta Vid
        {
            get
            {
                // *** Start programmer edit section *** (Departament.Vid Get start)

                // *** End programmer edit section *** (Departament.Vid Get start)
                EmberFlexberryDummy.VidDepartamenta result = this.fVid;
                // *** Start programmer edit section *** (Departament.Vid Get end)

                // *** End programmer edit section *** (Departament.Vid Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Departament.Vid Set start)

                // *** End programmer edit section *** (Departament.Vid Set start)
                this.fVid = value;
                // *** Start programmer edit section *** (Departament.Vid Set end)

                // *** End programmer edit section *** (Departament.Vid Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "DepartamentE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View DepartamentE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("DepartamentE", typeof(EmberFlexberryDummy.Departament));
                }
            }
            
            /// <summary>
            /// "DepartamentL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View DepartamentL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("DepartamentL", typeof(EmberFlexberryDummy.Departament));
                }
            }
        }
    }
}
