//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmberFlexberryDummy
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Detail.
    /// </summary>
    // *** Start programmer edit section *** (Detail CustomAttributes)

    // *** End programmer edit section *** (Detail CustomAttributes)
    [AutoAltered()]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("Detail", new string[] {
            "Name",
            "ParentDetail",
            "ParentDetail.Name"}, Hidden=new string[] {
            "ParentDetail.Name"})]
    [MasterViewDefineAttribute("Detail", "ParentDetail", ICSSoft.STORMNET.LookupTypeEnum.Standard, "", "Name")]
    public class Detail : ICSSoft.STORMNET.DataObject
    {
        
        private string fName;
        
        private EmberFlexberryDummy.Detail fParentDetail;
        
        private EmberFlexberryDummy.Master fMaster;
        
        // *** Start programmer edit section *** (Detail CustomMembers)

        // *** End programmer edit section *** (Detail CustomMembers)

        
        /// <summary>
        /// Name.
        /// </summary>
        // *** Start programmer edit section *** (Detail.Name CustomAttributes)

        // *** End programmer edit section *** (Detail.Name CustomAttributes)
        public virtual string Name
        {
            get
            {
                // *** Start programmer edit section *** (Detail.Name Get start)

                // *** End programmer edit section *** (Detail.Name Get start)
                string result = this.fName;
                // *** Start programmer edit section *** (Detail.Name Get end)

                // *** End programmer edit section *** (Detail.Name Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Detail.Name Set start)

                // *** End programmer edit section *** (Detail.Name Set start)
                this.fName = value;
                // *** Start programmer edit section *** (Detail.Name Set end)

                // *** End programmer edit section *** (Detail.Name Set end)
            }
        }
        
        /// <summary>
        /// Detail.
        /// </summary>
        // *** Start programmer edit section *** (Detail.ParentDetail CustomAttributes)

        // *** End programmer edit section *** (Detail.ParentDetail CustomAttributes)
        [PropertyStorage(new string[] {
                "ParentDetail"})]
        public virtual EmberFlexberryDummy.Detail ParentDetail
        {
            get
            {
                // *** Start programmer edit section *** (Detail.ParentDetail Get start)

                // *** End programmer edit section *** (Detail.ParentDetail Get start)
                EmberFlexberryDummy.Detail result = this.fParentDetail;
                // *** Start programmer edit section *** (Detail.ParentDetail Get end)

                // *** End programmer edit section *** (Detail.ParentDetail Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Detail.ParentDetail Set start)

                // *** End programmer edit section *** (Detail.ParentDetail Set start)
                this.fParentDetail = value;
                // *** Start programmer edit section *** (Detail.ParentDetail Set end)

                // *** End programmer edit section *** (Detail.ParentDetail Set end)
            }
        }
        
        /// <summary>
        /// мастеровая ссылка на шапку EmberFlexberryDummy.Master.
        /// </summary>
        // *** Start programmer edit section *** (Detail.Master CustomAttributes)

        // *** End programmer edit section *** (Detail.Master CustomAttributes)
        [Agregator()]
        [NotNull()]
        [PropertyStorage(new string[] {
                "Master"})]
        public virtual EmberFlexberryDummy.Master Master
        {
            get
            {
                // *** Start programmer edit section *** (Detail.Master Get start)

                // *** End programmer edit section *** (Detail.Master Get start)
                EmberFlexberryDummy.Master result = this.fMaster;
                // *** Start programmer edit section *** (Detail.Master Get end)

                // *** End programmer edit section *** (Detail.Master Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Detail.Master Set start)

                // *** End programmer edit section *** (Detail.Master Set start)
                this.fMaster = value;
                // *** Start programmer edit section *** (Detail.Master Set end)

                // *** End programmer edit section *** (Detail.Master Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "Detail" view.
            /// </summary>
            public static ICSSoft.STORMNET.View Detail
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("Detail", typeof(EmberFlexberryDummy.Detail));
                }
            }
        }
    }
    
    /// <summary>
    /// Detail array of Detail.
    /// </summary>
    // *** Start programmer edit section *** (DetailArrayDetailArrayOfDetail CustomAttributes)

    // *** End programmer edit section *** (DetailArrayDetailArrayOfDetail CustomAttributes)
    public class DetailArrayOfDetail : ICSSoft.STORMNET.DetailArray
    {
        
        // *** Start programmer edit section *** (EmberFlexberryDummy.DetailArrayOfDetail members)

        // *** End programmer edit section *** (EmberFlexberryDummy.DetailArrayOfDetail members)

        
        /// <summary>
        /// Construct detail array.
        /// </summary>
        /// <summary>
        /// Returns object with type Detail by index.
        /// </summary>
        /// <summary>
        /// Adds object with type Detail.
        /// </summary>
        public DetailArrayOfDetail(EmberFlexberryDummy.Master fMaster) : 
                base(typeof(Detail), ((ICSSoft.STORMNET.DataObject)(fMaster)))
        {
        }
        
        public EmberFlexberryDummy.Detail this[int index]
        {
            get
            {
                return ((EmberFlexberryDummy.Detail)(this.ItemByIndex(index)));
            }
        }
        
        public virtual void Add(EmberFlexberryDummy.Detail dataobject)
        {
            this.AddObject(((ICSSoft.STORMNET.DataObject)(dataobject)));
        }
    }
}
