//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmberFlexberryDummyPost
{
    using System;
    using System.Xml;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// EObj.
    /// </summary>
    // *** Start programmer edit section *** (EObj CustomAttributes)

    // *** End programmer edit section *** (EObj CustomAttributes)
    public class EObj
    {
        
        private string fEditor;
        
        // *** Start programmer edit section *** (EObj CustomMembers)

        // *** End programmer edit section *** (EObj CustomMembers)

        
        /// <summary>
        /// Editor.
        /// </summary>
        // *** Start programmer edit section *** (EObj.Editor CustomAttributes)

        // *** End programmer edit section *** (EObj.Editor CustomAttributes)
        public virtual string Editor
        {
            get
            {
                // *** Start programmer edit section *** (EObj.Editor Get start)

                // *** End programmer edit section *** (EObj.Editor Get start)
                string result = this.fEditor;
                // *** Start programmer edit section *** (EObj.Editor Get end)

                // *** End programmer edit section *** (EObj.Editor Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (EObj.Editor Set start)

                // *** End programmer edit section *** (EObj.Editor Set start)
                this.fEditor = value;
                // *** Start programmer edit section *** (EObj.Editor Set end)

                // *** End programmer edit section *** (EObj.Editor Set end)
            }
        }
    }
}
