//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmberFlexberryDummy
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Gender.
    /// </summary>
    // *** Start programmer edit section *** (Gender CustomAttributes)

    // *** End programmer edit section *** (Gender CustomAttributes)
    public enum Gender
    {
        
        // *** Start programmer edit section *** (Gender.Male CustomAttributes)

        // *** End programmer edit section *** (Gender.Male CustomAttributes)
        [Caption("Male")]
        Male,
        
        // *** Start programmer edit section *** (Gender.Female CustomAttributes)

        // *** End programmer edit section *** (Gender.Female CustomAttributes)
        [Caption("Female")]
        Female,
        
        // *** Start programmer edit section *** (Gender.Unknown CustomAttributes)

        // *** End programmer edit section *** (Gender.Unknown CustomAttributes)
        [Caption("")]
        Unknown,
    }
}
