//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmberFlexberryDummy
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// GraduateRecord.
    /// </summary>
    // *** Start programmer edit section *** (GraduateRecord CustomAttributes)

    // *** End programmer edit section *** (GraduateRecord CustomAttributes)
    [AutoAltered()]
    [ICSSoft.STORMNET.NotStored(false)]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("GraduateRecordE", new string[] {
            "GrFIO as \'ФИО\'",
            "GrYearGrad as \'Год выпуска\'",
            "UniquelD",
            "ObjectPK",
            "ShowName"}, Hidden=new string[] {
            "ShowName"})]
    public class GraduateRecord : EmberFlexberryDummy.StudyRecord
    {
        
        private string fGrFIO;
        
        private int fGrYearGrad;
        
        // *** Start programmer edit section *** (GraduateRecord CustomMembers)

        // *** End programmer edit section *** (GraduateRecord CustomMembers)

        
        /// <summary>
        /// GrFIO.
        /// </summary>
        // *** Start programmer edit section *** (GraduateRecord.GrFIO CustomAttributes)

        // *** End programmer edit section *** (GraduateRecord.GrFIO CustomAttributes)
        public virtual string GrFIO
        {
            get
            {
                // *** Start programmer edit section *** (GraduateRecord.GrFIO Get start)

                // *** End programmer edit section *** (GraduateRecord.GrFIO Get start)
                string result = this.fGrFIO;
                // *** Start programmer edit section *** (GraduateRecord.GrFIO Get end)

                // *** End programmer edit section *** (GraduateRecord.GrFIO Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (GraduateRecord.GrFIO Set start)

                // *** End programmer edit section *** (GraduateRecord.GrFIO Set start)
                this.fGrFIO = value;
                // *** Start programmer edit section *** (GraduateRecord.GrFIO Set end)

                // *** End programmer edit section *** (GraduateRecord.GrFIO Set end)
            }
        }
        
        /// <summary>
        /// GrYearGrad.
        /// </summary>
        // *** Start programmer edit section *** (GraduateRecord.GrYearGrad CustomAttributes)

        // *** End programmer edit section *** (GraduateRecord.GrYearGrad CustomAttributes)
        public virtual int GrYearGrad
        {
            get
            {
                // *** Start programmer edit section *** (GraduateRecord.GrYearGrad Get start)

                // *** End programmer edit section *** (GraduateRecord.GrYearGrad Get start)
                int result = this.fGrYearGrad;
                // *** Start programmer edit section *** (GraduateRecord.GrYearGrad Get end)

                // *** End programmer edit section *** (GraduateRecord.GrYearGrad Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (GraduateRecord.GrYearGrad Set start)

                // *** End programmer edit section *** (GraduateRecord.GrYearGrad Set start)
                this.fGrYearGrad = value;
                // *** Start programmer edit section *** (GraduateRecord.GrYearGrad Set end)

                // *** End programmer edit section *** (GraduateRecord.GrYearGrad Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "GraduateRecordE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View GraduateRecordE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("GraduateRecordE", typeof(EmberFlexberryDummy.GraduateRecord));
                }
            }
        }
    }
}
