//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmberFlexberryDummy
{
    using System;
    using System.Xml;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Inter.
    /// </summary>
    // *** Start programmer edit section *** (Inter CustomAttributes)

    // *** End programmer edit section *** (Inter CustomAttributes)
    public interface Inter
    {
        
        // *** Start programmer edit section *** (Inter CustomMembers)

        // *** End programmer edit section *** (Inter CustomMembers)

        
        /// <summary>
        /// TextIf.
        /// </summary>
        // *** Start programmer edit section *** (TextIf CustomAttributes)

        // *** End programmer edit section *** (TextIf CustomAttributes)
        string TextIf
        {
            get;
            set;
        }
    }
}
