//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmberFlexberryDummy
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// LazyLoadingMaster.
    /// </summary>
    // *** Start programmer edit section *** (LazyLoadingMaster CustomAttributes)

    // *** End programmer edit section *** (LazyLoadingMaster CustomAttributes)
    [AutoAltered()]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("LazyLoadingMasterEdit", new string[] {
            "MasterText as \'Master text\'"})]
    [AssociatedDetailViewAttribute("LazyLoadingMasterEdit", "LazyLoadingDetail", "LazyLoadingDetailEdit", true, "", "Detail", true, new string[] {
            ""})]
    [View("LazyLoadingMasterList", new string[] {
            "MasterText as \'Master text\'"})]
    public class LazyLoadingMaster : ICSSoft.STORMNET.DataObject
    {
        
        private string fMasterText;
        
        private EmberFlexberryDummy.DetailArrayOfLazyLoadingDetail fLazyLoadingDetail;
        
        // *** Start programmer edit section *** (LazyLoadingMaster CustomMembers)

        // *** End programmer edit section *** (LazyLoadingMaster CustomMembers)

        
        /// <summary>
        /// MasterText.
        /// </summary>
        // *** Start programmer edit section *** (LazyLoadingMaster.MasterText CustomAttributes)

        // *** End programmer edit section *** (LazyLoadingMaster.MasterText CustomAttributes)
        public virtual string MasterText
        {
            get
            {
                // *** Start programmer edit section *** (LazyLoadingMaster.MasterText Get start)

                // *** End programmer edit section *** (LazyLoadingMaster.MasterText Get start)
                string result = this.fMasterText;
                // *** Start programmer edit section *** (LazyLoadingMaster.MasterText Get end)

                // *** End programmer edit section *** (LazyLoadingMaster.MasterText Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (LazyLoadingMaster.MasterText Set start)

                // *** End programmer edit section *** (LazyLoadingMaster.MasterText Set start)
                this.fMasterText = value;
                // *** Start programmer edit section *** (LazyLoadingMaster.MasterText Set end)

                // *** End programmer edit section *** (LazyLoadingMaster.MasterText Set end)
            }
        }
        
        /// <summary>
        /// LazyLoadingMaster.
        /// </summary>
        // *** Start programmer edit section *** (LazyLoadingMaster.LazyLoadingDetail CustomAttributes)

        // *** End programmer edit section *** (LazyLoadingMaster.LazyLoadingDetail CustomAttributes)
        public virtual EmberFlexberryDummy.DetailArrayOfLazyLoadingDetail LazyLoadingDetail
        {
            get
            {
                // *** Start programmer edit section *** (LazyLoadingMaster.LazyLoadingDetail Get start)

                // *** End programmer edit section *** (LazyLoadingMaster.LazyLoadingDetail Get start)
                if ((this.fLazyLoadingDetail == null))
                {
                    this.fLazyLoadingDetail = new EmberFlexberryDummy.DetailArrayOfLazyLoadingDetail(this);
                }
                EmberFlexberryDummy.DetailArrayOfLazyLoadingDetail result = this.fLazyLoadingDetail;
                // *** Start programmer edit section *** (LazyLoadingMaster.LazyLoadingDetail Get end)

                // *** End programmer edit section *** (LazyLoadingMaster.LazyLoadingDetail Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (LazyLoadingMaster.LazyLoadingDetail Set start)

                // *** End programmer edit section *** (LazyLoadingMaster.LazyLoadingDetail Set start)
                this.fLazyLoadingDetail = value;
                // *** Start programmer edit section *** (LazyLoadingMaster.LazyLoadingDetail Set end)

                // *** End programmer edit section *** (LazyLoadingMaster.LazyLoadingDetail Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "LazyLoadingMasterEdit" view.
            /// </summary>
            public static ICSSoft.STORMNET.View LazyLoadingMasterEdit
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("LazyLoadingMasterEdit", typeof(EmberFlexberryDummy.LazyLoadingMaster));
                }
            }
            
            /// <summary>
            /// "LazyLoadingMasterList" view.
            /// </summary>
            public static ICSSoft.STORMNET.View LazyLoadingMasterList
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("LazyLoadingMasterList", typeof(EmberFlexberryDummy.LazyLoadingMaster));
                }
            }
        }
    }
}
