//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmberFlexberryDummy
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// LazyLoadingDetail.
    /// </summary>
    // *** Start programmer edit section *** (LazyLoadingDetail CustomAttributes)

    // *** End programmer edit section *** (LazyLoadingDetail CustomAttributes)
    [AutoAltered()]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("LazyLoadingDetailEdit", new string[] {
            "DetailText as \'Detail text\'"})]
    public class LazyLoadingDetail : ICSSoft.STORMNET.DataObject
    {
        
        private string fDetailText;
        
        private EmberFlexberryDummy.LazyLoadingMaster fLazyLoadingMaster;
        
        // *** Start programmer edit section *** (LazyLoadingDetail CustomMembers)

        // *** End programmer edit section *** (LazyLoadingDetail CustomMembers)

        
        /// <summary>
        /// DetailText.
        /// </summary>
        // *** Start programmer edit section *** (LazyLoadingDetail.DetailText CustomAttributes)

        // *** End programmer edit section *** (LazyLoadingDetail.DetailText CustomAttributes)
        public virtual string DetailText
        {
            get
            {
                // *** Start programmer edit section *** (LazyLoadingDetail.DetailText Get start)

                // *** End programmer edit section *** (LazyLoadingDetail.DetailText Get start)
                string result = this.fDetailText;
                // *** Start programmer edit section *** (LazyLoadingDetail.DetailText Get end)

                // *** End programmer edit section *** (LazyLoadingDetail.DetailText Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (LazyLoadingDetail.DetailText Set start)

                // *** End programmer edit section *** (LazyLoadingDetail.DetailText Set start)
                this.fDetailText = value;
                // *** Start programmer edit section *** (LazyLoadingDetail.DetailText Set end)

                // *** End programmer edit section *** (LazyLoadingDetail.DetailText Set end)
            }
        }
        
        /// <summary>
        /// мастеровая ссылка на шапку EmberFlexberryDummy.LazyLoadingMaster.
        /// </summary>
        // *** Start programmer edit section *** (LazyLoadingDetail.LazyLoadingMaster CustomAttributes)

        // *** End programmer edit section *** (LazyLoadingDetail.LazyLoadingMaster CustomAttributes)
        [Agregator()]
        [NotNull()]
        [PropertyStorage(new string[] {
                "LazyLoadingMaster"})]
        public virtual EmberFlexberryDummy.LazyLoadingMaster LazyLoadingMaster
        {
            get
            {
                // *** Start programmer edit section *** (LazyLoadingDetail.LazyLoadingMaster Get start)

                // *** End programmer edit section *** (LazyLoadingDetail.LazyLoadingMaster Get start)
                EmberFlexberryDummy.LazyLoadingMaster result = this.fLazyLoadingMaster;
                // *** Start programmer edit section *** (LazyLoadingDetail.LazyLoadingMaster Get end)

                // *** End programmer edit section *** (LazyLoadingDetail.LazyLoadingMaster Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (LazyLoadingDetail.LazyLoadingMaster Set start)

                // *** End programmer edit section *** (LazyLoadingDetail.LazyLoadingMaster Set start)
                this.fLazyLoadingMaster = value;
                // *** Start programmer edit section *** (LazyLoadingDetail.LazyLoadingMaster Set end)

                // *** End programmer edit section *** (LazyLoadingDetail.LazyLoadingMaster Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "LazyLoadingDetailEdit" view.
            /// </summary>
            public static ICSSoft.STORMNET.View LazyLoadingDetailEdit
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("LazyLoadingDetailEdit", typeof(EmberFlexberryDummy.LazyLoadingDetail));
                }
            }
        }
    }
    
    /// <summary>
    /// Detail array of LazyLoadingDetail.
    /// </summary>
    // *** Start programmer edit section *** (DetailArrayDetailArrayOfLazyLoadingDetail CustomAttributes)

    // *** End programmer edit section *** (DetailArrayDetailArrayOfLazyLoadingDetail CustomAttributes)
    public class DetailArrayOfLazyLoadingDetail : ICSSoft.STORMNET.DetailArray
    {
        
        // *** Start programmer edit section *** (EmberFlexberryDummy.DetailArrayOfLazyLoadingDetail members)

        // *** End programmer edit section *** (EmberFlexberryDummy.DetailArrayOfLazyLoadingDetail members)

        
        /// <summary>
        /// Construct detail array.
        /// </summary>
        /// <summary>
        /// Returns object with type LazyLoadingDetail by index.
        /// </summary>
        /// <summary>
        /// Adds object with type LazyLoadingDetail.
        /// </summary>
        public DetailArrayOfLazyLoadingDetail(EmberFlexberryDummy.LazyLoadingMaster fLazyLoadingMaster) : 
                base(typeof(LazyLoadingDetail), ((ICSSoft.STORMNET.DataObject)(fLazyLoadingMaster)))
        {
        }
        
        public EmberFlexberryDummy.LazyLoadingDetail this[int index]
        {
            get
            {
                return ((EmberFlexberryDummy.LazyLoadingDetail)(this.ItemByIndex(index)));
            }
        }
        
        public virtual void Add(EmberFlexberryDummy.LazyLoadingDetail dataobject)
        {
            this.AddObject(((ICSSoft.STORMNET.DataObject)(dataobject)));
        }
    }
}
