//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmberFlexberryDummy
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// listLocalization.
    /// </summary>
    // *** Start programmer edit section *** (listLocalization CustomAttributes)

    // *** End programmer edit section *** (listLocalization CustomAttributes)
    [AutoAltered()]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("listLocalizationD", new string[] {
            "name",
            "localeValue"})]
    public class listLocalization : ICSSoft.STORMNET.DataObject
    {
        
        private string fname;
        
        private string flocaleValue;
        
        private EmberFlexberryDummy.Catalog fCatalog;
        
        // *** Start programmer edit section *** (listLocalization CustomMembers)

        // *** End programmer edit section *** (listLocalization CustomMembers)

        
        /// <summary>
        /// name.
        /// </summary>
        // *** Start programmer edit section *** (listLocalization.name CustomAttributes)

        // *** End programmer edit section *** (listLocalization.name CustomAttributes)
        public virtual string name
        {
            get
            {
                // *** Start programmer edit section *** (listLocalization.name Get start)

                // *** End programmer edit section *** (listLocalization.name Get start)
                string result = this.fname;
                // *** Start programmer edit section *** (listLocalization.name Get end)

                // *** End programmer edit section *** (listLocalization.name Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (listLocalization.name Set start)

                // *** End programmer edit section *** (listLocalization.name Set start)
                this.fname = value;
                // *** Start programmer edit section *** (listLocalization.name Set end)

                // *** End programmer edit section *** (listLocalization.name Set end)
            }
        }
        
        /// <summary>
        /// localeValue.
        /// </summary>
        // *** Start programmer edit section *** (listLocalization.localeValue CustomAttributes)

        // *** End programmer edit section *** (listLocalization.localeValue CustomAttributes)
        public virtual string localeValue
        {
            get
            {
                // *** Start programmer edit section *** (listLocalization.localeValue Get start)

                // *** End programmer edit section *** (listLocalization.localeValue Get start)
                string result = this.flocaleValue;
                // *** Start programmer edit section *** (listLocalization.localeValue Get end)

                // *** End programmer edit section *** (listLocalization.localeValue Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (listLocalization.localeValue Set start)

                // *** End programmer edit section *** (listLocalization.localeValue Set start)
                this.flocaleValue = value;
                // *** Start programmer edit section *** (listLocalization.localeValue Set end)

                // *** End programmer edit section *** (listLocalization.localeValue Set end)
            }
        }
        
        /// <summary>
        /// мастеровая ссылка на шапку EmberFlexberryDummy.Catalog.
        /// </summary>
        // *** Start programmer edit section *** (listLocalization.Catalog CustomAttributes)

        // *** End programmer edit section *** (listLocalization.Catalog CustomAttributes)
        [Agregator()]
        [NotNull()]
        [PropertyStorage(new string[] {
                "Catalog"})]
        public virtual EmberFlexberryDummy.Catalog Catalog
        {
            get
            {
                // *** Start programmer edit section *** (listLocalization.Catalog Get start)

                // *** End programmer edit section *** (listLocalization.Catalog Get start)
                EmberFlexberryDummy.Catalog result = this.fCatalog;
                // *** Start programmer edit section *** (listLocalization.Catalog Get end)

                // *** End programmer edit section *** (listLocalization.Catalog Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (listLocalization.Catalog Set start)

                // *** End programmer edit section *** (listLocalization.Catalog Set start)
                this.fCatalog = value;
                // *** Start programmer edit section *** (listLocalization.Catalog Set end)

                // *** End programmer edit section *** (listLocalization.Catalog Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// Детейл для проверки локализации справочников.
            /// </summary>
            public static ICSSoft.STORMNET.View listLocalizationD
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("listLocalizationD", typeof(EmberFlexberryDummy.listLocalization));
                }
            }
        }
    }
    
    /// <summary>
    /// Detail array of listLocalization.
    /// </summary>
    // *** Start programmer edit section *** (DetailArrayDetailArrayOflistLocalization CustomAttributes)

    // *** End programmer edit section *** (DetailArrayDetailArrayOflistLocalization CustomAttributes)
    public class DetailArrayOflistLocalization : ICSSoft.STORMNET.DetailArray
    {
        
        // *** Start programmer edit section *** (EmberFlexberryDummy.DetailArrayOflistLocalization members)

        // *** End programmer edit section *** (EmberFlexberryDummy.DetailArrayOflistLocalization members)

        
        /// <summary>
        /// Construct detail array.
        /// </summary>
        /// <summary>
        /// Returns object with type listLocalization by index.
        /// </summary>
        /// <summary>
        /// Adds object with type listLocalization.
        /// </summary>
        public DetailArrayOflistLocalization(EmberFlexberryDummy.Catalog fCatalog) : 
                base(typeof(listLocalization), ((ICSSoft.STORMNET.DataObject)(fCatalog)))
        {
        }
        
        public EmberFlexberryDummy.listLocalization this[int index]
        {
            get
            {
                return ((EmberFlexberryDummy.listLocalization)(this.ItemByIndex(index)));
            }
        }
        
        public virtual void Add(EmberFlexberryDummy.listLocalization dataobject)
        {
            this.AddObject(((ICSSoft.STORMNET.DataObject)(dataobject)));
        }
    }
}
