//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmberFlexberryDummy
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    using ICSSoft.STORMNET.Business.Audit;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Localized suggestion type.
    /// </summary>
    // *** Start programmer edit section *** (LocalizedSuggestionType CustomAttributes)

    // *** End programmer edit section *** (LocalizedSuggestionType CustomAttributes)
    [AutoAltered()]
    [Caption("Localized suggestion type")]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("AuditView", new string[] {
            "Name as \'Name\'",
            "Localization as \'Localization\'",
            "Localization.Name as \'Name\'"}, Hidden=new string[] {
            "Localization.Name"})]
    [MasterViewDefineAttribute("AuditView", "Localization", ICSSoft.STORMNET.LookupTypeEnum.Standard, "", "Name")]
    [View("LocalizedSuggestionTypeE", new string[] {
            "Name as \'Name\'",
            "Localization as \'Localization\'",
            "Localization.Name as \'Name\'",
            "SuggestionType"}, Hidden=new string[] {
            "Localization.Name",
            "SuggestionType"})]
    [MasterViewDefineAttribute("LocalizedSuggestionTypeE", "Localization", ICSSoft.STORMNET.LookupTypeEnum.Standard, "", "Name")]
    public class LocalizedSuggestionType : ICSSoft.STORMNET.DataObject, IDataObjectWithAuditFields
    {
        
        private System.Nullable<System.DateTime> fCreateTime;
        
        private string fCreator;
        
        private System.Nullable<System.DateTime> fEditTime;
        
        private string fEditor;
        
        private string fName;
        
        private EmberFlexberryDummy.Localization fLocalization;
        
        private EmberFlexberryDummy.SuggestionType fSuggestionType;
        
        // *** Start programmer edit section *** (LocalizedSuggestionType CustomMembers)

        // *** End programmer edit section *** (LocalizedSuggestionType CustomMembers)

        
        /// <summary>
        /// Время создания объекта.
        /// </summary>
        // *** Start programmer edit section *** (LocalizedSuggestionType.CreateTime CustomAttributes)

        // *** End programmer edit section *** (LocalizedSuggestionType.CreateTime CustomAttributes)
        public virtual System.Nullable<System.DateTime> CreateTime
        {
            get
            {
                // *** Start programmer edit section *** (LocalizedSuggestionType.CreateTime Get start)

                // *** End programmer edit section *** (LocalizedSuggestionType.CreateTime Get start)
                System.Nullable<System.DateTime> result = this.fCreateTime;
                // *** Start programmer edit section *** (LocalizedSuggestionType.CreateTime Get end)

                // *** End programmer edit section *** (LocalizedSuggestionType.CreateTime Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (LocalizedSuggestionType.CreateTime Set start)

                // *** End programmer edit section *** (LocalizedSuggestionType.CreateTime Set start)
                this.fCreateTime = value;
                // *** Start programmer edit section *** (LocalizedSuggestionType.CreateTime Set end)

                // *** End programmer edit section *** (LocalizedSuggestionType.CreateTime Set end)
            }
        }
        
        /// <summary>
        /// Создатель объекта.
        /// </summary>
        // *** Start programmer edit section *** (LocalizedSuggestionType.Creator CustomAttributes)

        // *** End programmer edit section *** (LocalizedSuggestionType.Creator CustomAttributes)
        public virtual string Creator
        {
            get
            {
                // *** Start programmer edit section *** (LocalizedSuggestionType.Creator Get start)

                // *** End programmer edit section *** (LocalizedSuggestionType.Creator Get start)
                string result = this.fCreator;
                // *** Start programmer edit section *** (LocalizedSuggestionType.Creator Get end)

                // *** End programmer edit section *** (LocalizedSuggestionType.Creator Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (LocalizedSuggestionType.Creator Set start)

                // *** End programmer edit section *** (LocalizedSuggestionType.Creator Set start)
                this.fCreator = value;
                // *** Start programmer edit section *** (LocalizedSuggestionType.Creator Set end)

                // *** End programmer edit section *** (LocalizedSuggestionType.Creator Set end)
            }
        }
        
        /// <summary>
        /// Время последнего редактирования объекта.
        /// </summary>
        // *** Start programmer edit section *** (LocalizedSuggestionType.EditTime CustomAttributes)

        // *** End programmer edit section *** (LocalizedSuggestionType.EditTime CustomAttributes)
        public virtual System.Nullable<System.DateTime> EditTime
        {
            get
            {
                // *** Start programmer edit section *** (LocalizedSuggestionType.EditTime Get start)

                // *** End programmer edit section *** (LocalizedSuggestionType.EditTime Get start)
                System.Nullable<System.DateTime> result = this.fEditTime;
                // *** Start programmer edit section *** (LocalizedSuggestionType.EditTime Get end)

                // *** End programmer edit section *** (LocalizedSuggestionType.EditTime Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (LocalizedSuggestionType.EditTime Set start)

                // *** End programmer edit section *** (LocalizedSuggestionType.EditTime Set start)
                this.fEditTime = value;
                // *** Start programmer edit section *** (LocalizedSuggestionType.EditTime Set end)

                // *** End programmer edit section *** (LocalizedSuggestionType.EditTime Set end)
            }
        }
        
        /// <summary>
        /// Последний редактор объекта.
        /// </summary>
        // *** Start programmer edit section *** (LocalizedSuggestionType.Editor CustomAttributes)

        // *** End programmer edit section *** (LocalizedSuggestionType.Editor CustomAttributes)
        public virtual string Editor
        {
            get
            {
                // *** Start programmer edit section *** (LocalizedSuggestionType.Editor Get start)

                // *** End programmer edit section *** (LocalizedSuggestionType.Editor Get start)
                string result = this.fEditor;
                // *** Start programmer edit section *** (LocalizedSuggestionType.Editor Get end)

                // *** End programmer edit section *** (LocalizedSuggestionType.Editor Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (LocalizedSuggestionType.Editor Set start)

                // *** End programmer edit section *** (LocalizedSuggestionType.Editor Set start)
                this.fEditor = value;
                // *** Start programmer edit section *** (LocalizedSuggestionType.Editor Set end)

                // *** End programmer edit section *** (LocalizedSuggestionType.Editor Set end)
            }
        }
        
        /// <summary>
        /// Name.
        /// </summary>
        // *** Start programmer edit section *** (LocalizedSuggestionType.Name CustomAttributes)

        // *** End programmer edit section *** (LocalizedSuggestionType.Name CustomAttributes)
        [NotNull()]
        public virtual string Name
        {
            get
            {
                // *** Start programmer edit section *** (LocalizedSuggestionType.Name Get start)

                // *** End programmer edit section *** (LocalizedSuggestionType.Name Get start)
                string result = this.fName;
                // *** Start programmer edit section *** (LocalizedSuggestionType.Name Get end)

                // *** End programmer edit section *** (LocalizedSuggestionType.Name Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (LocalizedSuggestionType.Name Set start)

                // *** End programmer edit section *** (LocalizedSuggestionType.Name Set start)
                this.fName = value;
                // *** Start programmer edit section *** (LocalizedSuggestionType.Name Set end)

                // *** End programmer edit section *** (LocalizedSuggestionType.Name Set end)
            }
        }
        
        /// <summary>
        /// Localized suggestion type.
        /// </summary>
        // *** Start programmer edit section *** (LocalizedSuggestionType.Localization CustomAttributes)

        // *** End programmer edit section *** (LocalizedSuggestionType.Localization CustomAttributes)
        [PropertyStorage(new string[] {
                "Localization"})]
        [NotNull()]
        public virtual EmberFlexberryDummy.Localization Localization
        {
            get
            {
                // *** Start programmer edit section *** (LocalizedSuggestionType.Localization Get start)

                // *** End programmer edit section *** (LocalizedSuggestionType.Localization Get start)
                EmberFlexberryDummy.Localization result = this.fLocalization;
                // *** Start programmer edit section *** (LocalizedSuggestionType.Localization Get end)

                // *** End programmer edit section *** (LocalizedSuggestionType.Localization Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (LocalizedSuggestionType.Localization Set start)

                // *** End programmer edit section *** (LocalizedSuggestionType.Localization Set start)
                this.fLocalization = value;
                // *** Start programmer edit section *** (LocalizedSuggestionType.Localization Set end)

                // *** End programmer edit section *** (LocalizedSuggestionType.Localization Set end)
            }
        }
        
        /// <summary>
        /// мастеровая ссылка на шапку EmberFlexberryDummy.SuggestionType.
        /// </summary>
        // *** Start programmer edit section *** (LocalizedSuggestionType.SuggestionType CustomAttributes)

        // *** End programmer edit section *** (LocalizedSuggestionType.SuggestionType CustomAttributes)
        [Agregator()]
        [NotNull()]
        [PropertyStorage(new string[] {
                "SuggestionType"})]
        public virtual EmberFlexberryDummy.SuggestionType SuggestionType
        {
            get
            {
                // *** Start programmer edit section *** (LocalizedSuggestionType.SuggestionType Get start)

                // *** End programmer edit section *** (LocalizedSuggestionType.SuggestionType Get start)
                EmberFlexberryDummy.SuggestionType result = this.fSuggestionType;
                // *** Start programmer edit section *** (LocalizedSuggestionType.SuggestionType Get end)

                // *** End programmer edit section *** (LocalizedSuggestionType.SuggestionType Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (LocalizedSuggestionType.SuggestionType Set start)

                // *** End programmer edit section *** (LocalizedSuggestionType.SuggestionType Set start)
                this.fSuggestionType = value;
                // *** Start programmer edit section *** (LocalizedSuggestionType.SuggestionType Set end)

                // *** End programmer edit section *** (LocalizedSuggestionType.SuggestionType Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "AuditView" view.
            /// </summary>
            public static ICSSoft.STORMNET.View AuditView
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("AuditView", typeof(EmberFlexberryDummy.LocalizedSuggestionType));
                }
            }
            
            /// <summary>
            /// "LocalizedSuggestionTypeE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View LocalizedSuggestionTypeE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("LocalizedSuggestionTypeE", typeof(EmberFlexberryDummy.LocalizedSuggestionType));
                }
            }
        }
    }
    
    /// <summary>
    /// Detail array of LocalizedSuggestionType.
    /// </summary>
    // *** Start programmer edit section *** (DetailArrayDetailArrayOfLocalizedSuggestionType CustomAttributes)

    // *** End programmer edit section *** (DetailArrayDetailArrayOfLocalizedSuggestionType CustomAttributes)
    public class DetailArrayOfLocalizedSuggestionType : ICSSoft.STORMNET.DetailArray
    {
        
        // *** Start programmer edit section *** (EmberFlexberryDummy.DetailArrayOfLocalizedSuggestionType members)

        // *** End programmer edit section *** (EmberFlexberryDummy.DetailArrayOfLocalizedSuggestionType members)

        
        /// <summary>
        /// Construct detail array.
        /// </summary>
        /// <summary>
        /// Returns object with type LocalizedSuggestionType by index.
        /// </summary>
        /// <summary>
        /// Adds object with type LocalizedSuggestionType.
        /// </summary>
        public DetailArrayOfLocalizedSuggestionType(EmberFlexberryDummy.SuggestionType fSuggestionType) : 
                base(typeof(LocalizedSuggestionType), ((ICSSoft.STORMNET.DataObject)(fSuggestionType)))
        {
        }
        
        public EmberFlexberryDummy.LocalizedSuggestionType this[int index]
        {
            get
            {
                return ((EmberFlexberryDummy.LocalizedSuggestionType)(this.ItemByIndex(index)));
            }
        }
        
        public virtual void Add(EmberFlexberryDummy.LocalizedSuggestionType dataobject)
        {
            this.AddObject(((ICSSoft.STORMNET.DataObject)(dataobject)));
        }
    }
}
