//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmberFlexberryDummy
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    using ICSSoft.STORMNET.Business.Audit;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Localization.
    /// </summary>
    // *** Start programmer edit section *** (Localization CustomAttributes)

    // *** End programmer edit section *** (Localization CustomAttributes)
    [AutoAltered()]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("AuditView", new string[] {
            "Name as \'Name\'"})]
    [View("LocalizationE", new string[] {
            "Name as \'Name\'"})]
    [View("LocalizationL", new string[] {
            "Name as \'Name\'"})]
    public class Localization : ICSSoft.STORMNET.DataObject, IDataObjectWithAuditFields
    {
        
        private System.Nullable<System.DateTime> fCreateTime;
        
        private string fCreator;
        
        private System.Nullable<System.DateTime> fEditTime;
        
        private string fEditor;
        
        private string fName;
        
        // *** Start programmer edit section *** (Localization CustomMembers)

        // *** End programmer edit section *** (Localization CustomMembers)

        
        /// <summary>
        /// Время создания объекта.
        /// </summary>
        // *** Start programmer edit section *** (Localization.CreateTime CustomAttributes)

        // *** End programmer edit section *** (Localization.CreateTime CustomAttributes)
        public virtual System.Nullable<System.DateTime> CreateTime
        {
            get
            {
                // *** Start programmer edit section *** (Localization.CreateTime Get start)

                // *** End programmer edit section *** (Localization.CreateTime Get start)
                System.Nullable<System.DateTime> result = this.fCreateTime;
                // *** Start programmer edit section *** (Localization.CreateTime Get end)

                // *** End programmer edit section *** (Localization.CreateTime Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Localization.CreateTime Set start)

                // *** End programmer edit section *** (Localization.CreateTime Set start)
                this.fCreateTime = value;
                // *** Start programmer edit section *** (Localization.CreateTime Set end)

                // *** End programmer edit section *** (Localization.CreateTime Set end)
            }
        }
        
        /// <summary>
        /// Создатель объекта.
        /// </summary>
        // *** Start programmer edit section *** (Localization.Creator CustomAttributes)

        // *** End programmer edit section *** (Localization.Creator CustomAttributes)
        public virtual string Creator
        {
            get
            {
                // *** Start programmer edit section *** (Localization.Creator Get start)

                // *** End programmer edit section *** (Localization.Creator Get start)
                string result = this.fCreator;
                // *** Start programmer edit section *** (Localization.Creator Get end)

                // *** End programmer edit section *** (Localization.Creator Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Localization.Creator Set start)

                // *** End programmer edit section *** (Localization.Creator Set start)
                this.fCreator = value;
                // *** Start programmer edit section *** (Localization.Creator Set end)

                // *** End programmer edit section *** (Localization.Creator Set end)
            }
        }
        
        /// <summary>
        /// Время последнего редактирования объекта.
        /// </summary>
        // *** Start programmer edit section *** (Localization.EditTime CustomAttributes)

        // *** End programmer edit section *** (Localization.EditTime CustomAttributes)
        public virtual System.Nullable<System.DateTime> EditTime
        {
            get
            {
                // *** Start programmer edit section *** (Localization.EditTime Get start)

                // *** End programmer edit section *** (Localization.EditTime Get start)
                System.Nullable<System.DateTime> result = this.fEditTime;
                // *** Start programmer edit section *** (Localization.EditTime Get end)

                // *** End programmer edit section *** (Localization.EditTime Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Localization.EditTime Set start)

                // *** End programmer edit section *** (Localization.EditTime Set start)
                this.fEditTime = value;
                // *** Start programmer edit section *** (Localization.EditTime Set end)

                // *** End programmer edit section *** (Localization.EditTime Set end)
            }
        }
        
        /// <summary>
        /// Последний редактор объекта.
        /// </summary>
        // *** Start programmer edit section *** (Localization.Editor CustomAttributes)

        // *** End programmer edit section *** (Localization.Editor CustomAttributes)
        public virtual string Editor
        {
            get
            {
                // *** Start programmer edit section *** (Localization.Editor Get start)

                // *** End programmer edit section *** (Localization.Editor Get start)
                string result = this.fEditor;
                // *** Start programmer edit section *** (Localization.Editor Get end)

                // *** End programmer edit section *** (Localization.Editor Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Localization.Editor Set start)

                // *** End programmer edit section *** (Localization.Editor Set start)
                this.fEditor = value;
                // *** Start programmer edit section *** (Localization.Editor Set end)

                // *** End programmer edit section *** (Localization.Editor Set end)
            }
        }
        
        /// <summary>
        /// Name.
        /// </summary>
        // *** Start programmer edit section *** (Localization.Name CustomAttributes)

        // *** End programmer edit section *** (Localization.Name CustomAttributes)
        [NotNull()]
        public virtual string Name
        {
            get
            {
                // *** Start programmer edit section *** (Localization.Name Get start)

                // *** End programmer edit section *** (Localization.Name Get start)
                string result = this.fName;
                // *** Start programmer edit section *** (Localization.Name Get end)

                // *** End programmer edit section *** (Localization.Name Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Localization.Name Set start)

                // *** End programmer edit section *** (Localization.Name Set start)
                this.fName = value;
                // *** Start programmer edit section *** (Localization.Name Set end)

                // *** End programmer edit section *** (Localization.Name Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "AuditView" view.
            /// </summary>
            public static ICSSoft.STORMNET.View AuditView
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("AuditView", typeof(EmberFlexberryDummy.Localization));
                }
            }
            
            /// <summary>
            /// "LocalizationE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View LocalizationE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("LocalizationE", typeof(EmberFlexberryDummy.Localization));
                }
            }
            
            /// <summary>
            /// "LocalizationL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View LocalizationL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("LocalizationL", typeof(EmberFlexberryDummy.Localization));
                }
            }
        }
    }
}
