//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmberFlexberryDummy
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// MasterLookupDropdown.
    /// </summary>
    // *** Start programmer edit section *** (MasterLookupDropdown CustomAttributes)

    // *** End programmer edit section *** (MasterLookupDropdown CustomAttributes)
    [AutoAltered()]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("MasterLookupDropdown", new string[] {
            "Text as \'Text\'"})]
    public class MasterLookupDropdown : ICSSoft.STORMNET.DataObject
    {
        
        private string fText;
        
        // *** Start programmer edit section *** (MasterLookupDropdown CustomMembers)

        // *** End programmer edit section *** (MasterLookupDropdown CustomMembers)

        
        /// <summary>
        /// Text.
        /// </summary>
        // *** Start programmer edit section *** (MasterLookupDropdown.Text CustomAttributes)

        // *** End programmer edit section *** (MasterLookupDropdown.Text CustomAttributes)
        public virtual string Text
        {
            get
            {
                // *** Start programmer edit section *** (MasterLookupDropdown.Text Get start)

                // *** End programmer edit section *** (MasterLookupDropdown.Text Get start)
                string result = this.fText;
                // *** Start programmer edit section *** (MasterLookupDropdown.Text Get end)

                // *** End programmer edit section *** (MasterLookupDropdown.Text Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (MasterLookupDropdown.Text Set start)

                // *** End programmer edit section *** (MasterLookupDropdown.Text Set start)
                this.fText = value;
                // *** Start programmer edit section *** (MasterLookupDropdown.Text Set end)

                // *** End programmer edit section *** (MasterLookupDropdown.Text Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// Представление для проверки лукапа-дропдауна на форме редактирования.
            /// </summary>
            public static ICSSoft.STORMNET.View MasterLookupDropdown
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("MasterLookupDropdown", typeof(EmberFlexberryDummy.MasterLookupDropdown));
                }
            }
        }
    }
}
