//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmberFlexberryDummy
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Master.
    /// </summary>
    // *** Start programmer edit section *** (Master CustomAttributes)

    // *** End programmer edit section *** (Master CustomAttributes)
    [AutoAltered()]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("MasterEdit", new string[] {
            "Name as \'Name\'"})]
    [AssociatedDetailViewAttribute("MasterEdit", "Detail", "Detail", true, "", "Detail", true, new string[] {
            ""})]
    [View("MasterList", new string[] {
            "Name as \'Name\'"})]
    public class Master : ICSSoft.STORMNET.DataObject
    {
        
        private string fName;
        
        private EmberFlexberryDummy.DetailArrayOfDetail fDetail;
        
        // *** Start programmer edit section *** (Master CustomMembers)

        // *** End programmer edit section *** (Master CustomMembers)

        
        /// <summary>
        /// Name.
        /// </summary>
        // *** Start programmer edit section *** (Master.Name CustomAttributes)

        // *** End programmer edit section *** (Master.Name CustomAttributes)
        public virtual string Name
        {
            get
            {
                // *** Start programmer edit section *** (Master.Name Get start)

                // *** End programmer edit section *** (Master.Name Get start)
                string result = this.fName;
                // *** Start programmer edit section *** (Master.Name Get end)

                // *** End programmer edit section *** (Master.Name Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Master.Name Set start)

                // *** End programmer edit section *** (Master.Name Set start)
                this.fName = value;
                // *** Start programmer edit section *** (Master.Name Set end)

                // *** End programmer edit section *** (Master.Name Set end)
            }
        }
        
        /// <summary>
        /// Master.
        /// </summary>
        // *** Start programmer edit section *** (Master.Detail CustomAttributes)

        // *** End programmer edit section *** (Master.Detail CustomAttributes)
        public virtual EmberFlexberryDummy.DetailArrayOfDetail Detail
        {
            get
            {
                // *** Start programmer edit section *** (Master.Detail Get start)

                // *** End programmer edit section *** (Master.Detail Get start)
                if ((this.fDetail == null))
                {
                    this.fDetail = new EmberFlexberryDummy.DetailArrayOfDetail(this);
                }
                EmberFlexberryDummy.DetailArrayOfDetail result = this.fDetail;
                // *** Start programmer edit section *** (Master.Detail Get end)

                // *** End programmer edit section *** (Master.Detail Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Master.Detail Set start)

                // *** End programmer edit section *** (Master.Detail Set start)
                this.fDetail = value;
                // *** Start programmer edit section *** (Master.Detail Set end)

                // *** End programmer edit section *** (Master.Detail Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "MasterEdit" view.
            /// </summary>
            public static ICSSoft.STORMNET.View MasterEdit
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("MasterEdit", typeof(EmberFlexberryDummy.Master));
                }
            }
            
            /// <summary>
            /// "MasterList" view.
            /// </summary>
            public static ICSSoft.STORMNET.View MasterList
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("MasterList", typeof(EmberFlexberryDummy.Master));
                }
            }
        }
    }
}
