//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmberFlexberryDummy
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// StudentRecord.
    /// </summary>
    // *** Start programmer edit section *** (StudentRecord CustomAttributes)

    // *** End programmer edit section *** (StudentRecord CustomAttributes)
    [AutoAltered()]
    [ICSSoft.STORMNET.NotStored(false)]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("StudentRecordE", new string[] {
            "SrFIO as \'ФИО\'",
            "SrCours as \'Курс\'",
            "UniquelD",
            "ObjectPK",
            "ShowName"}, Hidden=new string[] {
            "ShowName"})]
    public class StudentRecord : EmberFlexberryDummy.StudyRecord
    {
        
        private string fSrFIO;
        
        private int fSrCours;
        
        // *** Start programmer edit section *** (StudentRecord CustomMembers)

        // *** End programmer edit section *** (StudentRecord CustomMembers)

        
        /// <summary>
        /// SrFIO.
        /// </summary>
        // *** Start programmer edit section *** (StudentRecord.SrFIO CustomAttributes)

        // *** End programmer edit section *** (StudentRecord.SrFIO CustomAttributes)
        public virtual string SrFIO
        {
            get
            {
                // *** Start programmer edit section *** (StudentRecord.SrFIO Get start)

                // *** End programmer edit section *** (StudentRecord.SrFIO Get start)
                string result = this.fSrFIO;
                // *** Start programmer edit section *** (StudentRecord.SrFIO Get end)

                // *** End programmer edit section *** (StudentRecord.SrFIO Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (StudentRecord.SrFIO Set start)

                // *** End programmer edit section *** (StudentRecord.SrFIO Set start)
                this.fSrFIO = value;
                // *** Start programmer edit section *** (StudentRecord.SrFIO Set end)

                // *** End programmer edit section *** (StudentRecord.SrFIO Set end)
            }
        }
        
        /// <summary>
        /// SrCours.
        /// </summary>
        // *** Start programmer edit section *** (StudentRecord.SrCours CustomAttributes)

        // *** End programmer edit section *** (StudentRecord.SrCours CustomAttributes)
        public virtual int SrCours
        {
            get
            {
                // *** Start programmer edit section *** (StudentRecord.SrCours Get start)

                // *** End programmer edit section *** (StudentRecord.SrCours Get start)
                int result = this.fSrCours;
                // *** Start programmer edit section *** (StudentRecord.SrCours Get end)

                // *** End programmer edit section *** (StudentRecord.SrCours Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (StudentRecord.SrCours Set start)

                // *** End programmer edit section *** (StudentRecord.SrCours Set start)
                this.fSrCours = value;
                // *** Start programmer edit section *** (StudentRecord.SrCours Set end)

                // *** End programmer edit section *** (StudentRecord.SrCours Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "StudentRecordE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View StudentRecordE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("StudentRecordE", typeof(EmberFlexberryDummy.StudentRecord));
                }
            }
        }
    }
}
