//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmberFlexberryDummy
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// StudyRecord.
    /// </summary>
    // *** Start programmer edit section *** (StudyRecord CustomAttributes)

    // *** End programmer edit section *** (StudyRecord CustomAttributes)
    [AutoAltered()]
    [ICSSoft.STORMNET.NotStored()]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("StudyRecordL", new string[] {
            "UniquelD",
            "ObjectPK",
            "ShowName"}, Hidden=new string[] {
            "ShowName"})]
    public class StudyRecord : ICSSoft.STORMNET.DataObject
    {
        
        private string fUniquelD;
        
        private int fObjectPK;
        
        // *** Start programmer edit section *** (StudyRecord CustomMembers)

        // *** End programmer edit section *** (StudyRecord CustomMembers)

        
        /// <summary>
        /// UniquelD.
        /// </summary>
        // *** Start programmer edit section *** (StudyRecord.UniquelD CustomAttributes)

        // *** End programmer edit section *** (StudyRecord.UniquelD CustomAttributes)
        public virtual string UniquelD
        {
            get
            {
                // *** Start programmer edit section *** (StudyRecord.UniquelD Get start)

                // *** End programmer edit section *** (StudyRecord.UniquelD Get start)
                string result = this.fUniquelD;
                // *** Start programmer edit section *** (StudyRecord.UniquelD Get end)

                // *** End programmer edit section *** (StudyRecord.UniquelD Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (StudyRecord.UniquelD Set start)

                // *** End programmer edit section *** (StudyRecord.UniquelD Set start)
                this.fUniquelD = value;
                // *** Start programmer edit section *** (StudyRecord.UniquelD Set end)

                // *** End programmer edit section *** (StudyRecord.UniquelD Set end)
            }
        }
        
        /// <summary>
        /// ObjectPK.
        /// </summary>
        // *** Start programmer edit section *** (StudyRecord.ObjectPK CustomAttributes)

        // *** End programmer edit section *** (StudyRecord.ObjectPK CustomAttributes)
        public virtual int ObjectPK
        {
            get
            {
                // *** Start programmer edit section *** (StudyRecord.ObjectPK Get start)

                // *** End programmer edit section *** (StudyRecord.ObjectPK Get start)
                int result = this.fObjectPK;
                // *** Start programmer edit section *** (StudyRecord.ObjectPK Get end)

                // *** End programmer edit section *** (StudyRecord.ObjectPK Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (StudyRecord.ObjectPK Set start)

                // *** End programmer edit section *** (StudyRecord.ObjectPK Set start)
                this.fObjectPK = value;
                // *** Start programmer edit section *** (StudyRecord.ObjectPK Set end)

                // *** End programmer edit section *** (StudyRecord.ObjectPK Set end)
            }
        }
        
        /// <summary>
        /// ShowName.
        /// </summary>
        // *** Start programmer edit section *** (StudyRecord.ShowName CustomAttributes)

        // *** End programmer edit section *** (StudyRecord.ShowName CustomAttributes)
        [ICSSoft.STORMNET.NotStored()]
        public virtual string ShowName
        {
            get
            {
                // *** Start programmer edit section *** (StudyRecord.ShowName Get)

                return null;
                // *** End programmer edit section *** (StudyRecord.ShowName Get)
            }
            set
            {
                // *** Start programmer edit section *** (StudyRecord.ShowName Set)

                // *** End programmer edit section *** (StudyRecord.ShowName Set)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "StudyRecordL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View StudyRecordL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("StudyRecordL", typeof(EmberFlexberryDummy.StudyRecord));
                }
            }
        }
    }
}
