//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmberFlexberryDummy
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// SuccessorSocialNetwork.
    /// </summary>
    // *** Start programmer edit section *** (SuccessorSocialNetwork CustomAttributes)

    // *** End programmer edit section *** (SuccessorSocialNetwork CustomAttributes)
    [AutoAltered()]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("SuccessorE", new string[] {
            "Name as \'Name\'",
            "VK as \'VK\'",
            "Facebook as \'Facebook\'",
            "Twitter as \'Twitter\'"})]
    [View("SuccessorL", new string[] {
            "Name as \'Name\'",
            "VK as \'VK\'",
            "Facebook as \'Facebook\'",
            "Twitter as \'Twitter\'"})]
    public class SuccessorSocialNetwork : EmberFlexberryDummy.Parent
    {
        
        private string fVK;
        
        private string fFacebook;
        
        private string fTwitter;
        
        // *** Start programmer edit section *** (SuccessorSocialNetwork CustomMembers)

        // *** End programmer edit section *** (SuccessorSocialNetwork CustomMembers)

        
        /// <summary>
        /// VK.
        /// </summary>
        // *** Start programmer edit section *** (SuccessorSocialNetwork.VK CustomAttributes)

        // *** End programmer edit section *** (SuccessorSocialNetwork.VK CustomAttributes)
        public virtual string VK
        {
            get
            {
                // *** Start programmer edit section *** (SuccessorSocialNetwork.VK Get start)

                // *** End programmer edit section *** (SuccessorSocialNetwork.VK Get start)
                string result = this.fVK;
                // *** Start programmer edit section *** (SuccessorSocialNetwork.VK Get end)

                // *** End programmer edit section *** (SuccessorSocialNetwork.VK Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (SuccessorSocialNetwork.VK Set start)

                // *** End programmer edit section *** (SuccessorSocialNetwork.VK Set start)
                this.fVK = value;
                // *** Start programmer edit section *** (SuccessorSocialNetwork.VK Set end)

                // *** End programmer edit section *** (SuccessorSocialNetwork.VK Set end)
            }
        }
        
        /// <summary>
        /// Facebook.
        /// </summary>
        // *** Start programmer edit section *** (SuccessorSocialNetwork.Facebook CustomAttributes)

        // *** End programmer edit section *** (SuccessorSocialNetwork.Facebook CustomAttributes)
        public virtual string Facebook
        {
            get
            {
                // *** Start programmer edit section *** (SuccessorSocialNetwork.Facebook Get start)

                // *** End programmer edit section *** (SuccessorSocialNetwork.Facebook Get start)
                string result = this.fFacebook;
                // *** Start programmer edit section *** (SuccessorSocialNetwork.Facebook Get end)

                // *** End programmer edit section *** (SuccessorSocialNetwork.Facebook Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (SuccessorSocialNetwork.Facebook Set start)

                // *** End programmer edit section *** (SuccessorSocialNetwork.Facebook Set start)
                this.fFacebook = value;
                // *** Start programmer edit section *** (SuccessorSocialNetwork.Facebook Set end)

                // *** End programmer edit section *** (SuccessorSocialNetwork.Facebook Set end)
            }
        }
        
        /// <summary>
        /// Twitter.
        /// </summary>
        // *** Start programmer edit section *** (SuccessorSocialNetwork.Twitter CustomAttributes)

        // *** End programmer edit section *** (SuccessorSocialNetwork.Twitter CustomAttributes)
        public virtual string Twitter
        {
            get
            {
                // *** Start programmer edit section *** (SuccessorSocialNetwork.Twitter Get start)

                // *** End programmer edit section *** (SuccessorSocialNetwork.Twitter Get start)
                string result = this.fTwitter;
                // *** Start programmer edit section *** (SuccessorSocialNetwork.Twitter Get end)

                // *** End programmer edit section *** (SuccessorSocialNetwork.Twitter Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (SuccessorSocialNetwork.Twitter Set start)

                // *** End programmer edit section *** (SuccessorSocialNetwork.Twitter Set start)
                this.fTwitter = value;
                // *** Start programmer edit section *** (SuccessorSocialNetwork.Twitter Set end)

                // *** End programmer edit section *** (SuccessorSocialNetwork.Twitter Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "SuccessorE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View SuccessorE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("SuccessorE", typeof(EmberFlexberryDummy.SuccessorSocialNetwork));
                }
            }
            
            /// <summary>
            /// "SuccessorL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View SuccessorL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("SuccessorL", typeof(EmberFlexberryDummy.SuccessorSocialNetwork));
                }
            }
        }
    }
}
