//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmberFlexberryDummy
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// SuccessorPhone.
    /// </summary>
    // *** Start programmer edit section *** (SuccessorPhone CustomAttributes)

    // *** End programmer edit section *** (SuccessorPhone CustomAttributes)
    [AutoAltered()]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("SuccessorE", new string[] {
            "Name as \'Name\'",
            "Phone1 as \'Phone1\'",
            "Phone2 as \'Phone2\'",
            "Phone3 as \'Phone3\'"})]
    [View("SuccessorL", new string[] {
            "Name as \'Name\'",
            "Phone1 as \'Phone1\'",
            "Phone2 as \'Phone2\'",
            "Phone3 as \'Phone3\'"})]
    public class SuccessorPhone : EmberFlexberryDummy.Parent
    {
        
        private string fPhone1;
        
        private string fPhone2;
        
        private string fPhone3;
        
        // *** Start programmer edit section *** (SuccessorPhone CustomMembers)

        // *** End programmer edit section *** (SuccessorPhone CustomMembers)

        
        /// <summary>
        /// Phone1.
        /// </summary>
        // *** Start programmer edit section *** (SuccessorPhone.Phone1 CustomAttributes)

        // *** End programmer edit section *** (SuccessorPhone.Phone1 CustomAttributes)
        public virtual string Phone1
        {
            get
            {
                // *** Start programmer edit section *** (SuccessorPhone.Phone1 Get start)

                // *** End programmer edit section *** (SuccessorPhone.Phone1 Get start)
                string result = this.fPhone1;
                // *** Start programmer edit section *** (SuccessorPhone.Phone1 Get end)

                // *** End programmer edit section *** (SuccessorPhone.Phone1 Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (SuccessorPhone.Phone1 Set start)

                // *** End programmer edit section *** (SuccessorPhone.Phone1 Set start)
                this.fPhone1 = value;
                // *** Start programmer edit section *** (SuccessorPhone.Phone1 Set end)

                // *** End programmer edit section *** (SuccessorPhone.Phone1 Set end)
            }
        }
        
        /// <summary>
        /// Phone2.
        /// </summary>
        // *** Start programmer edit section *** (SuccessorPhone.Phone2 CustomAttributes)

        // *** End programmer edit section *** (SuccessorPhone.Phone2 CustomAttributes)
        public virtual string Phone2
        {
            get
            {
                // *** Start programmer edit section *** (SuccessorPhone.Phone2 Get start)

                // *** End programmer edit section *** (SuccessorPhone.Phone2 Get start)
                string result = this.fPhone2;
                // *** Start programmer edit section *** (SuccessorPhone.Phone2 Get end)

                // *** End programmer edit section *** (SuccessorPhone.Phone2 Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (SuccessorPhone.Phone2 Set start)

                // *** End programmer edit section *** (SuccessorPhone.Phone2 Set start)
                this.fPhone2 = value;
                // *** Start programmer edit section *** (SuccessorPhone.Phone2 Set end)

                // *** End programmer edit section *** (SuccessorPhone.Phone2 Set end)
            }
        }
        
        /// <summary>
        /// Phone3.
        /// </summary>
        // *** Start programmer edit section *** (SuccessorPhone.Phone3 CustomAttributes)

        // *** End programmer edit section *** (SuccessorPhone.Phone3 CustomAttributes)
        public virtual string Phone3
        {
            get
            {
                // *** Start programmer edit section *** (SuccessorPhone.Phone3 Get start)

                // *** End programmer edit section *** (SuccessorPhone.Phone3 Get start)
                string result = this.fPhone3;
                // *** Start programmer edit section *** (SuccessorPhone.Phone3 Get end)

                // *** End programmer edit section *** (SuccessorPhone.Phone3 Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (SuccessorPhone.Phone3 Set start)

                // *** End programmer edit section *** (SuccessorPhone.Phone3 Set start)
                this.fPhone3 = value;
                // *** Start programmer edit section *** (SuccessorPhone.Phone3 Set end)

                // *** End programmer edit section *** (SuccessorPhone.Phone3 Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "SuccessorE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View SuccessorE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("SuccessorE", typeof(EmberFlexberryDummy.SuccessorPhone));
                }
            }
            
            /// <summary>
            /// "SuccessorL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View SuccessorL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("SuccessorL", typeof(EmberFlexberryDummy.SuccessorPhone));
                }
            }
        }
    }
}
