//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmberFlexberryDummy
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    using ICSSoft.STORMNET.Business.Audit;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Suggestion file.
    /// </summary>
    // *** Start programmer edit section *** (SuggestionFile CustomAttributes)

    // *** End programmer edit section *** (SuggestionFile CustomAttributes)
    [AutoAltered()]
    [Caption("Suggestion file")]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("AuditView", new string[] {
            "Order as \'Order\'",
            "File as \'File\'"})]
    [View("SuggestionFileE", new string[] {
            "Order as \'Order\'",
            "File as \'File\'",
            "Suggestion"}, Hidden=new string[] {
            "Suggestion"})]
    public class SuggestionFile : ICSSoft.STORMNET.DataObject, IDataObjectWithAuditFields
    {
        
        private System.Nullable<System.DateTime> fCreateTime;
        
        private string fCreator;
        
        private System.Nullable<System.DateTime> fEditTime;
        
        private string fEditor;
        
        private int fOrder;
        
        private ICSSoft.STORMNET.UserDataTypes.WebFile fFile;
        
        private EmberFlexberryDummy.Suggestion fSuggestion;
        
        // *** Start programmer edit section *** (SuggestionFile CustomMembers)

        // *** End programmer edit section *** (SuggestionFile CustomMembers)

        
        /// <summary>
        /// Время создания объекта.
        /// </summary>
        // *** Start programmer edit section *** (SuggestionFile.CreateTime CustomAttributes)

        // *** End programmer edit section *** (SuggestionFile.CreateTime CustomAttributes)
        public virtual System.Nullable<System.DateTime> CreateTime
        {
            get
            {
                // *** Start programmer edit section *** (SuggestionFile.CreateTime Get start)

                // *** End programmer edit section *** (SuggestionFile.CreateTime Get start)
                System.Nullable<System.DateTime> result = this.fCreateTime;
                // *** Start programmer edit section *** (SuggestionFile.CreateTime Get end)

                // *** End programmer edit section *** (SuggestionFile.CreateTime Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (SuggestionFile.CreateTime Set start)

                // *** End programmer edit section *** (SuggestionFile.CreateTime Set start)
                this.fCreateTime = value;
                // *** Start programmer edit section *** (SuggestionFile.CreateTime Set end)

                // *** End programmer edit section *** (SuggestionFile.CreateTime Set end)
            }
        }
        
        /// <summary>
        /// Создатель объекта.
        /// </summary>
        // *** Start programmer edit section *** (SuggestionFile.Creator CustomAttributes)

        // *** End programmer edit section *** (SuggestionFile.Creator CustomAttributes)
        public virtual string Creator
        {
            get
            {
                // *** Start programmer edit section *** (SuggestionFile.Creator Get start)

                // *** End programmer edit section *** (SuggestionFile.Creator Get start)
                string result = this.fCreator;
                // *** Start programmer edit section *** (SuggestionFile.Creator Get end)

                // *** End programmer edit section *** (SuggestionFile.Creator Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (SuggestionFile.Creator Set start)

                // *** End programmer edit section *** (SuggestionFile.Creator Set start)
                this.fCreator = value;
                // *** Start programmer edit section *** (SuggestionFile.Creator Set end)

                // *** End programmer edit section *** (SuggestionFile.Creator Set end)
            }
        }
        
        /// <summary>
        /// Время последнего редактирования объекта.
        /// </summary>
        // *** Start programmer edit section *** (SuggestionFile.EditTime CustomAttributes)

        // *** End programmer edit section *** (SuggestionFile.EditTime CustomAttributes)
        public virtual System.Nullable<System.DateTime> EditTime
        {
            get
            {
                // *** Start programmer edit section *** (SuggestionFile.EditTime Get start)

                // *** End programmer edit section *** (SuggestionFile.EditTime Get start)
                System.Nullable<System.DateTime> result = this.fEditTime;
                // *** Start programmer edit section *** (SuggestionFile.EditTime Get end)

                // *** End programmer edit section *** (SuggestionFile.EditTime Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (SuggestionFile.EditTime Set start)

                // *** End programmer edit section *** (SuggestionFile.EditTime Set start)
                this.fEditTime = value;
                // *** Start programmer edit section *** (SuggestionFile.EditTime Set end)

                // *** End programmer edit section *** (SuggestionFile.EditTime Set end)
            }
        }
        
        /// <summary>
        /// Последний редактор объекта.
        /// </summary>
        // *** Start programmer edit section *** (SuggestionFile.Editor CustomAttributes)

        // *** End programmer edit section *** (SuggestionFile.Editor CustomAttributes)
        public virtual string Editor
        {
            get
            {
                // *** Start programmer edit section *** (SuggestionFile.Editor Get start)

                // *** End programmer edit section *** (SuggestionFile.Editor Get start)
                string result = this.fEditor;
                // *** Start programmer edit section *** (SuggestionFile.Editor Get end)

                // *** End programmer edit section *** (SuggestionFile.Editor Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (SuggestionFile.Editor Set start)

                // *** End programmer edit section *** (SuggestionFile.Editor Set start)
                this.fEditor = value;
                // *** Start programmer edit section *** (SuggestionFile.Editor Set end)

                // *** End programmer edit section *** (SuggestionFile.Editor Set end)
            }
        }
        
        /// <summary>
        /// Order.
        /// </summary>
        // *** Start programmer edit section *** (SuggestionFile.Order CustomAttributes)

        // *** End programmer edit section *** (SuggestionFile.Order CustomAttributes)
        [Order()]
        public virtual int Order
        {
            get
            {
                // *** Start programmer edit section *** (SuggestionFile.Order Get start)

                // *** End programmer edit section *** (SuggestionFile.Order Get start)
                int result = this.fOrder;
                // *** Start programmer edit section *** (SuggestionFile.Order Get end)

                // *** End programmer edit section *** (SuggestionFile.Order Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (SuggestionFile.Order Set start)

                // *** End programmer edit section *** (SuggestionFile.Order Set start)
                this.fOrder = value;
                // *** Start programmer edit section *** (SuggestionFile.Order Set end)

                // *** End programmer edit section *** (SuggestionFile.Order Set end)
            }
        }
        
        /// <summary>
        /// File.
        /// </summary>
        // *** Start programmer edit section *** (SuggestionFile.File CustomAttributes)

        // *** End programmer edit section *** (SuggestionFile.File CustomAttributes)
        public virtual ICSSoft.STORMNET.UserDataTypes.WebFile File
        {
            get
            {
                // *** Start programmer edit section *** (SuggestionFile.File Get start)

                // *** End programmer edit section *** (SuggestionFile.File Get start)
                ICSSoft.STORMNET.UserDataTypes.WebFile result = this.fFile;
                // *** Start programmer edit section *** (SuggestionFile.File Get end)

                // *** End programmer edit section *** (SuggestionFile.File Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (SuggestionFile.File Set start)

                // *** End programmer edit section *** (SuggestionFile.File Set start)
                this.fFile = value;
                // *** Start programmer edit section *** (SuggestionFile.File Set end)

                // *** End programmer edit section *** (SuggestionFile.File Set end)
            }
        }
        
        /// <summary>
        /// мастеровая ссылка на шапку EmberFlexberryDummy.Suggestion.
        /// </summary>
        // *** Start programmer edit section *** (SuggestionFile.Suggestion CustomAttributes)

        // *** End programmer edit section *** (SuggestionFile.Suggestion CustomAttributes)
        [Agregator()]
        [NotNull()]
        [PropertyStorage(new string[] {
                "Suggestion"})]
        [TypeUsage(new string[] {
                "EmberFlexberryDummy.Suggestion"})]
        public virtual EmberFlexberryDummy.Suggestion Suggestion
        {
            get
            {
                // *** Start programmer edit section *** (SuggestionFile.Suggestion Get start)

                // *** End programmer edit section *** (SuggestionFile.Suggestion Get start)
                EmberFlexberryDummy.Suggestion result = this.fSuggestion;
                // *** Start programmer edit section *** (SuggestionFile.Suggestion Get end)

                // *** End programmer edit section *** (SuggestionFile.Suggestion Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (SuggestionFile.Suggestion Set start)

                // *** End programmer edit section *** (SuggestionFile.Suggestion Set start)
                this.fSuggestion = value;
                // *** Start programmer edit section *** (SuggestionFile.Suggestion Set end)

                // *** End programmer edit section *** (SuggestionFile.Suggestion Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "AuditView" view.
            /// </summary>
            public static ICSSoft.STORMNET.View AuditView
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("AuditView", typeof(EmberFlexberryDummy.SuggestionFile));
                }
            }
            
            /// <summary>
            /// "SuggestionFileE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View SuggestionFileE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("SuggestionFileE", typeof(EmberFlexberryDummy.SuggestionFile));
                }
            }
        }
    }
    
    /// <summary>
    /// Detail array of SuggestionFile.
    /// </summary>
    // *** Start programmer edit section *** (DetailArrayDetailArrayOfSuggestionFile CustomAttributes)

    // *** End programmer edit section *** (DetailArrayDetailArrayOfSuggestionFile CustomAttributes)
    public class DetailArrayOfSuggestionFile : ICSSoft.STORMNET.DetailArray
    {
        
        // *** Start programmer edit section *** (EmberFlexberryDummy.DetailArrayOfSuggestionFile members)

        // *** End programmer edit section *** (EmberFlexberryDummy.DetailArrayOfSuggestionFile members)

        
        /// <summary>
        /// Construct detail array.
        /// </summary>
        /// <summary>
        /// Returns object with type SuggestionFile by index.
        /// </summary>
        /// <summary>
        /// Adds object with type SuggestionFile.
        /// </summary>
        public DetailArrayOfSuggestionFile(EmberFlexberryDummy.Suggestion fSuggestion) : 
                base(typeof(SuggestionFile), ((ICSSoft.STORMNET.DataObject)(fSuggestion)))
        {
        }
        
        public EmberFlexberryDummy.SuggestionFile this[int index]
        {
            get
            {
                return ((EmberFlexberryDummy.SuggestionFile)(this.ItemByIndex(index)));
            }
        }
        
        public virtual void Add(EmberFlexberryDummy.SuggestionFile dataobject)
        {
            this.AddObject(((ICSSoft.STORMNET.DataObject)(dataobject)));
        }
    }
}
