//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmberFlexberryDummy
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// TestPolyAnotherChild.
    /// </summary>
    // *** Start programmer edit section *** (TestPolyAnotherChild CustomAttributes)

    // *** End programmer edit section *** (TestPolyAnotherChild CustomAttributes)
    [AutoAltered()]
    [ICSSoft.STORMNET.NotStored(false)]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("TestPolyAnotherChildEdit", new string[] {
            "Pole",
            "ChildAnotherPole"})]
    [View("TestPolyAnotherChildList", new string[] {
            "Pole",
            "ChildAnotherPole"})]
    public class TestPolyAnotherChild : EmberFlexberryDummy.TestPolyBase
    {
        
        private bool fChildAnotherPole;
        
        // *** Start programmer edit section *** (TestPolyAnotherChild CustomMembers)

        // *** End programmer edit section *** (TestPolyAnotherChild CustomMembers)

        
        /// <summary>
        /// ChildAnotherPole.
        /// </summary>
        // *** Start programmer edit section *** (TestPolyAnotherChild.ChildAnotherPole CustomAttributes)

        // *** End programmer edit section *** (TestPolyAnotherChild.ChildAnotherPole CustomAttributes)
        public virtual bool ChildAnotherPole
        {
            get
            {
                // *** Start programmer edit section *** (TestPolyAnotherChild.ChildAnotherPole Get start)

                // *** End programmer edit section *** (TestPolyAnotherChild.ChildAnotherPole Get start)
                bool result = this.fChildAnotherPole;
                // *** Start programmer edit section *** (TestPolyAnotherChild.ChildAnotherPole Get end)

                // *** End programmer edit section *** (TestPolyAnotherChild.ChildAnotherPole Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (TestPolyAnotherChild.ChildAnotherPole Set start)

                // *** End programmer edit section *** (TestPolyAnotherChild.ChildAnotherPole Set start)
                this.fChildAnotherPole = value;
                // *** Start programmer edit section *** (TestPolyAnotherChild.ChildAnotherPole Set end)

                // *** End programmer edit section *** (TestPolyAnotherChild.ChildAnotherPole Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "TestPolyAnotherChildEdit" view.
            /// </summary>
            public static ICSSoft.STORMNET.View TestPolyAnotherChildEdit
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("TestPolyAnotherChildEdit", typeof(EmberFlexberryDummy.TestPolyAnotherChild));
                }
            }
            
            /// <summary>
            /// "TestPolyAnotherChildList" view.
            /// </summary>
            public static ICSSoft.STORMNET.View TestPolyAnotherChildList
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("TestPolyAnotherChildList", typeof(EmberFlexberryDummy.TestPolyAnotherChild));
                }
            }
        }
    }
}
