//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmberFlexberryDummy
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// TogglerExampleDetail.
    /// </summary>
    // *** Start programmer edit section *** (TogglerExampleDetail CustomAttributes)

    // *** End programmer edit section *** (TogglerExampleDetail CustomAttributes)
    [AutoAltered()]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("TogglerExampleDetailE", new string[] {
            "TogglerExampleDetailProperty as \'Наименование детейла\'"})]
    [View("TogglerExampleDetailL", new string[] {
            "TogglerExampleDetailProperty as \'Наименование детейла\'"})]
    public class TogglerExampleDetail : ICSSoft.STORMNET.DataObject
    {
        
        private string fTogglerExampleDetailProperty;
        
        private EmberFlexberryDummy.TogglerExampleMaster fTogglerExampleMaster;
        
        // *** Start programmer edit section *** (TogglerExampleDetail CustomMembers)

        // *** End programmer edit section *** (TogglerExampleDetail CustomMembers)

        
        /// <summary>
        /// TogglerExampleDetailProperty.
        /// </summary>
        // *** Start programmer edit section *** (TogglerExampleDetail.TogglerExampleDetailProperty CustomAttributes)

        // *** End programmer edit section *** (TogglerExampleDetail.TogglerExampleDetailProperty CustomAttributes)
        public virtual string TogglerExampleDetailProperty
        {
            get
            {
                // *** Start programmer edit section *** (TogglerExampleDetail.TogglerExampleDetailProperty Get start)

                // *** End programmer edit section *** (TogglerExampleDetail.TogglerExampleDetailProperty Get start)
                string result = this.fTogglerExampleDetailProperty;
                // *** Start programmer edit section *** (TogglerExampleDetail.TogglerExampleDetailProperty Get end)

                // *** End programmer edit section *** (TogglerExampleDetail.TogglerExampleDetailProperty Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (TogglerExampleDetail.TogglerExampleDetailProperty Set start)

                // *** End programmer edit section *** (TogglerExampleDetail.TogglerExampleDetailProperty Set start)
                this.fTogglerExampleDetailProperty = value;
                // *** Start programmer edit section *** (TogglerExampleDetail.TogglerExampleDetailProperty Set end)

                // *** End programmer edit section *** (TogglerExampleDetail.TogglerExampleDetailProperty Set end)
            }
        }
        
        /// <summary>
        /// мастеровая ссылка на шапку EmberFlexberryDummy.TogglerExampleMaster.
        /// </summary>
        // *** Start programmer edit section *** (TogglerExampleDetail.TogglerExampleMaster CustomAttributes)

        // *** End programmer edit section *** (TogglerExampleDetail.TogglerExampleMaster CustomAttributes)
        [Agregator()]
        [NotNull()]
        [PropertyStorage(new string[] {
                "TogglerExampleMaster"})]
        public virtual EmberFlexberryDummy.TogglerExampleMaster TogglerExampleMaster
        {
            get
            {
                // *** Start programmer edit section *** (TogglerExampleDetail.TogglerExampleMaster Get start)

                // *** End programmer edit section *** (TogglerExampleDetail.TogglerExampleMaster Get start)
                EmberFlexberryDummy.TogglerExampleMaster result = this.fTogglerExampleMaster;
                // *** Start programmer edit section *** (TogglerExampleDetail.TogglerExampleMaster Get end)

                // *** End programmer edit section *** (TogglerExampleDetail.TogglerExampleMaster Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (TogglerExampleDetail.TogglerExampleMaster Set start)

                // *** End programmer edit section *** (TogglerExampleDetail.TogglerExampleMaster Set start)
                this.fTogglerExampleMaster = value;
                // *** Start programmer edit section *** (TogglerExampleDetail.TogglerExampleMaster Set end)

                // *** End programmer edit section *** (TogglerExampleDetail.TogglerExampleMaster Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "TogglerExampleDetailE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View TogglerExampleDetailE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("TogglerExampleDetailE", typeof(EmberFlexberryDummy.TogglerExampleDetail));
                }
            }
            
            /// <summary>
            /// "TogglerExampleDetailL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View TogglerExampleDetailL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("TogglerExampleDetailL", typeof(EmberFlexberryDummy.TogglerExampleDetail));
                }
            }
        }
    }
    
    /// <summary>
    /// Detail array of TogglerExampleDetail.
    /// </summary>
    // *** Start programmer edit section *** (DetailArrayDetailArrayOfTogglerExampleDetail CustomAttributes)

    // *** End programmer edit section *** (DetailArrayDetailArrayOfTogglerExampleDetail CustomAttributes)
    public class DetailArrayOfTogglerExampleDetail : ICSSoft.STORMNET.DetailArray
    {
        
        // *** Start programmer edit section *** (EmberFlexberryDummy.DetailArrayOfTogglerExampleDetail members)

        // *** End programmer edit section *** (EmberFlexberryDummy.DetailArrayOfTogglerExampleDetail members)

        
        /// <summary>
        /// Construct detail array.
        /// </summary>
        /// <summary>
        /// Returns object with type TogglerExampleDetail by index.
        /// </summary>
        /// <summary>
        /// Adds object with type TogglerExampleDetail.
        /// </summary>
        public DetailArrayOfTogglerExampleDetail(EmberFlexberryDummy.TogglerExampleMaster fTogglerExampleMaster) : 
                base(typeof(TogglerExampleDetail), ((ICSSoft.STORMNET.DataObject)(fTogglerExampleMaster)))
        {
        }
        
        public EmberFlexberryDummy.TogglerExampleDetail this[int index]
        {
            get
            {
                return ((EmberFlexberryDummy.TogglerExampleDetail)(this.ItemByIndex(index)));
            }
        }
        
        public virtual void Add(EmberFlexberryDummy.TogglerExampleDetail dataobject)
        {
            this.AddObject(((ICSSoft.STORMNET.DataObject)(dataobject)));
        }
    }
}
