//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmberFlexberryDummy
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// TogglerExampleMaster.
    /// </summary>
    // *** Start programmer edit section *** (TogglerExampleMaster CustomAttributes)

    // *** End programmer edit section *** (TogglerExampleMaster CustomAttributes)
    [AutoAltered()]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("TogglerExampleMasterE", new string[] {
            "TogglerExampleMasterProperty as \'Наименование мастера\'"})]
    [AssociatedDetailViewAttribute("TogglerExampleMasterE", "TogglerExampleDetail", "TogglerExampleDetailL", true, "", "", true, new string[] {
            ""})]
    [View("TogglerExampleMasterL", new string[] {
            "TogglerExampleMasterProperty as \'Наименование мастера\'"})]
    [AssociatedDetailViewAttribute("TogglerExampleMasterL", "TogglerExampleDetail", "TogglerExampleDetailL", true, "", "", true, new string[] {
            ""})]
    public class TogglerExampleMaster : ICSSoft.STORMNET.DataObject
    {
        
        private string fTogglerExampleMasterProperty;
        
        private EmberFlexberryDummy.DetailArrayOfTogglerExampleDetail fTogglerExampleDetail;
        
        // *** Start programmer edit section *** (TogglerExampleMaster CustomMembers)

        // *** End programmer edit section *** (TogglerExampleMaster CustomMembers)

        
        /// <summary>
        /// TogglerExampleMasterProperty.
        /// </summary>
        // *** Start programmer edit section *** (TogglerExampleMaster.TogglerExampleMasterProperty CustomAttributes)

        // *** End programmer edit section *** (TogglerExampleMaster.TogglerExampleMasterProperty CustomAttributes)
        public virtual string TogglerExampleMasterProperty
        {
            get
            {
                // *** Start programmer edit section *** (TogglerExampleMaster.TogglerExampleMasterProperty Get start)

                // *** End programmer edit section *** (TogglerExampleMaster.TogglerExampleMasterProperty Get start)
                string result = this.fTogglerExampleMasterProperty;
                // *** Start programmer edit section *** (TogglerExampleMaster.TogglerExampleMasterProperty Get end)

                // *** End programmer edit section *** (TogglerExampleMaster.TogglerExampleMasterProperty Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (TogglerExampleMaster.TogglerExampleMasterProperty Set start)

                // *** End programmer edit section *** (TogglerExampleMaster.TogglerExampleMasterProperty Set start)
                this.fTogglerExampleMasterProperty = value;
                // *** Start programmer edit section *** (TogglerExampleMaster.TogglerExampleMasterProperty Set end)

                // *** End programmer edit section *** (TogglerExampleMaster.TogglerExampleMasterProperty Set end)
            }
        }
        
        /// <summary>
        /// TogglerExampleMaster.
        /// </summary>
        // *** Start programmer edit section *** (TogglerExampleMaster.TogglerExampleDetail CustomAttributes)

        // *** End programmer edit section *** (TogglerExampleMaster.TogglerExampleDetail CustomAttributes)
        public virtual EmberFlexberryDummy.DetailArrayOfTogglerExampleDetail TogglerExampleDetail
        {
            get
            {
                // *** Start programmer edit section *** (TogglerExampleMaster.TogglerExampleDetail Get start)

                // *** End programmer edit section *** (TogglerExampleMaster.TogglerExampleDetail Get start)
                if ((this.fTogglerExampleDetail == null))
                {
                    this.fTogglerExampleDetail = new EmberFlexberryDummy.DetailArrayOfTogglerExampleDetail(this);
                }
                EmberFlexberryDummy.DetailArrayOfTogglerExampleDetail result = this.fTogglerExampleDetail;
                // *** Start programmer edit section *** (TogglerExampleMaster.TogglerExampleDetail Get end)

                // *** End programmer edit section *** (TogglerExampleMaster.TogglerExampleDetail Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (TogglerExampleMaster.TogglerExampleDetail Set start)

                // *** End programmer edit section *** (TogglerExampleMaster.TogglerExampleDetail Set start)
                this.fTogglerExampleDetail = value;
                // *** Start programmer edit section *** (TogglerExampleMaster.TogglerExampleDetail Set end)

                // *** End programmer edit section *** (TogglerExampleMaster.TogglerExampleDetail Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "TogglerExampleMasterE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View TogglerExampleMasterE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("TogglerExampleMasterE", typeof(EmberFlexberryDummy.TogglerExampleMaster));
                }
            }
            
            /// <summary>
            /// "TogglerExampleMasterL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View TogglerExampleMasterL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("TogglerExampleMasterL", typeof(EmberFlexberryDummy.TogglerExampleMaster));
                }
            }
        }
    }
}
