//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmberFlexberryDummy
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    using ICSSoft.STORMNET.Business.Audit;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Vote.
    /// </summary>
    // *** Start programmer edit section *** (Vote CustomAttributes)

    // *** End programmer edit section *** (Vote CustomAttributes)
    [AutoAltered()]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("AuditView", new string[] {
            "VoteType as \'Vote type\'",
            "Author",
            "Author.Name"}, Hidden=new string[] {
            "Author.Name"})]
    [MasterViewDefineAttribute("AuditView", "Author", ICSSoft.STORMNET.LookupTypeEnum.Standard, "", "Name")]
    [View("VoteE", new string[] {
            "VoteType as \'Vote type\'",
            "Suggestion",
            "Author",
            "Author.Name"}, Hidden=new string[] {
            "Suggestion",
            "Author.Name"})]
    [MasterViewDefineAttribute("VoteE", "Author", ICSSoft.STORMNET.LookupTypeEnum.Standard, "", "Name")]
    public class Vote : ICSSoft.STORMNET.DataObject, IDataObjectWithAuditFields
    {
        
        private System.Nullable<System.DateTime> fCreateTime;
        
        private string fCreator;
        
        private System.Nullable<System.DateTime> fEditTime;
        
        private string fEditor;
        
        private EmberFlexberryDummy.VoteType fVoteType;
        
        private EmberFlexberryDummy.ApplicationUser fAuthor;
        
        private EmberFlexberryDummy.Suggestion fSuggestion;
        
        // *** Start programmer edit section *** (Vote CustomMembers)

        // *** End programmer edit section *** (Vote CustomMembers)

        
        /// <summary>
        /// Время создания объекта.
        /// </summary>
        // *** Start programmer edit section *** (Vote.CreateTime CustomAttributes)

        // *** End programmer edit section *** (Vote.CreateTime CustomAttributes)
        public virtual System.Nullable<System.DateTime> CreateTime
        {
            get
            {
                // *** Start programmer edit section *** (Vote.CreateTime Get start)

                // *** End programmer edit section *** (Vote.CreateTime Get start)
                System.Nullable<System.DateTime> result = this.fCreateTime;
                // *** Start programmer edit section *** (Vote.CreateTime Get end)

                // *** End programmer edit section *** (Vote.CreateTime Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Vote.CreateTime Set start)

                // *** End programmer edit section *** (Vote.CreateTime Set start)
                this.fCreateTime = value;
                // *** Start programmer edit section *** (Vote.CreateTime Set end)

                // *** End programmer edit section *** (Vote.CreateTime Set end)
            }
        }
        
        /// <summary>
        /// Создатель объекта.
        /// </summary>
        // *** Start programmer edit section *** (Vote.Creator CustomAttributes)

        // *** End programmer edit section *** (Vote.Creator CustomAttributes)
        public virtual string Creator
        {
            get
            {
                // *** Start programmer edit section *** (Vote.Creator Get start)

                // *** End programmer edit section *** (Vote.Creator Get start)
                string result = this.fCreator;
                // *** Start programmer edit section *** (Vote.Creator Get end)

                // *** End programmer edit section *** (Vote.Creator Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Vote.Creator Set start)

                // *** End programmer edit section *** (Vote.Creator Set start)
                this.fCreator = value;
                // *** Start programmer edit section *** (Vote.Creator Set end)

                // *** End programmer edit section *** (Vote.Creator Set end)
            }
        }
        
        /// <summary>
        /// Время последнего редактирования объекта.
        /// </summary>
        // *** Start programmer edit section *** (Vote.EditTime CustomAttributes)

        // *** End programmer edit section *** (Vote.EditTime CustomAttributes)
        public virtual System.Nullable<System.DateTime> EditTime
        {
            get
            {
                // *** Start programmer edit section *** (Vote.EditTime Get start)

                // *** End programmer edit section *** (Vote.EditTime Get start)
                System.Nullable<System.DateTime> result = this.fEditTime;
                // *** Start programmer edit section *** (Vote.EditTime Get end)

                // *** End programmer edit section *** (Vote.EditTime Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Vote.EditTime Set start)

                // *** End programmer edit section *** (Vote.EditTime Set start)
                this.fEditTime = value;
                // *** Start programmer edit section *** (Vote.EditTime Set end)

                // *** End programmer edit section *** (Vote.EditTime Set end)
            }
        }
        
        /// <summary>
        /// Последний редактор объекта.
        /// </summary>
        // *** Start programmer edit section *** (Vote.Editor CustomAttributes)

        // *** End programmer edit section *** (Vote.Editor CustomAttributes)
        public virtual string Editor
        {
            get
            {
                // *** Start programmer edit section *** (Vote.Editor Get start)

                // *** End programmer edit section *** (Vote.Editor Get start)
                string result = this.fEditor;
                // *** Start programmer edit section *** (Vote.Editor Get end)

                // *** End programmer edit section *** (Vote.Editor Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Vote.Editor Set start)

                // *** End programmer edit section *** (Vote.Editor Set start)
                this.fEditor = value;
                // *** Start programmer edit section *** (Vote.Editor Set end)

                // *** End programmer edit section *** (Vote.Editor Set end)
            }
        }
        
        /// <summary>
        /// VoteType.
        /// </summary>
        // *** Start programmer edit section *** (Vote.VoteType CustomAttributes)

        // *** End programmer edit section *** (Vote.VoteType CustomAttributes)
        public virtual EmberFlexberryDummy.VoteType VoteType
        {
            get
            {
                // *** Start programmer edit section *** (Vote.VoteType Get start)

                // *** End programmer edit section *** (Vote.VoteType Get start)
                EmberFlexberryDummy.VoteType result = this.fVoteType;
                // *** Start programmer edit section *** (Vote.VoteType Get end)

                // *** End programmer edit section *** (Vote.VoteType Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Vote.VoteType Set start)

                // *** End programmer edit section *** (Vote.VoteType Set start)
                this.fVoteType = value;
                // *** Start programmer edit section *** (Vote.VoteType Set end)

                // *** End programmer edit section *** (Vote.VoteType Set end)
            }
        }
        
        /// <summary>
        /// Vote.
        /// </summary>
        // *** Start programmer edit section *** (Vote.Author CustomAttributes)

        // *** End programmer edit section *** (Vote.Author CustomAttributes)
        [PropertyStorage(new string[] {
                "ApplicationUser"})]
        [NotNull()]
        public virtual EmberFlexberryDummy.ApplicationUser Author
        {
            get
            {
                // *** Start programmer edit section *** (Vote.Author Get start)

                // *** End programmer edit section *** (Vote.Author Get start)
                EmberFlexberryDummy.ApplicationUser result = this.fAuthor;
                // *** Start programmer edit section *** (Vote.Author Get end)

                // *** End programmer edit section *** (Vote.Author Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Vote.Author Set start)

                // *** End programmer edit section *** (Vote.Author Set start)
                this.fAuthor = value;
                // *** Start programmer edit section *** (Vote.Author Set end)

                // *** End programmer edit section *** (Vote.Author Set end)
            }
        }
        
        /// <summary>
        /// мастеровая ссылка на шапку EmberFlexberryDummy.Suggestion.
        /// </summary>
        // *** Start programmer edit section *** (Vote.Suggestion CustomAttributes)

        // *** End programmer edit section *** (Vote.Suggestion CustomAttributes)
        [Agregator()]
        [NotNull()]
        [PropertyStorage(new string[] {
                "Suggestion"})]
        [TypeUsage(new string[] {
                "EmberFlexberryDummy.Suggestion"})]
        public virtual EmberFlexberryDummy.Suggestion Suggestion
        {
            get
            {
                // *** Start programmer edit section *** (Vote.Suggestion Get start)

                // *** End programmer edit section *** (Vote.Suggestion Get start)
                EmberFlexberryDummy.Suggestion result = this.fSuggestion;
                // *** Start programmer edit section *** (Vote.Suggestion Get end)

                // *** End programmer edit section *** (Vote.Suggestion Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Vote.Suggestion Set start)

                // *** End programmer edit section *** (Vote.Suggestion Set start)
                this.fSuggestion = value;
                // *** Start programmer edit section *** (Vote.Suggestion Set end)

                // *** End programmer edit section *** (Vote.Suggestion Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "AuditView" view.
            /// </summary>
            public static ICSSoft.STORMNET.View AuditView
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("AuditView", typeof(EmberFlexberryDummy.Vote));
                }
            }
            
            /// <summary>
            /// "VoteE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View VoteE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("VoteE", typeof(EmberFlexberryDummy.Vote));
                }
            }
        }
    }
    
    /// <summary>
    /// Detail array of Vote.
    /// </summary>
    // *** Start programmer edit section *** (DetailArrayDetailArrayOfVote CustomAttributes)

    // *** End programmer edit section *** (DetailArrayDetailArrayOfVote CustomAttributes)
    public class DetailArrayOfVote : ICSSoft.STORMNET.DetailArray
    {
        
        // *** Start programmer edit section *** (EmberFlexberryDummy.DetailArrayOfVote members)

        // *** End programmer edit section *** (EmberFlexberryDummy.DetailArrayOfVote members)

        
        /// <summary>
        /// Construct detail array.
        /// </summary>
        /// <summary>
        /// Returns object with type Vote by index.
        /// </summary>
        /// <summary>
        /// Adds object with type Vote.
        /// </summary>
        public DetailArrayOfVote(EmberFlexberryDummy.Suggestion fSuggestion) : 
                base(typeof(Vote), ((ICSSoft.STORMNET.DataObject)(fSuggestion)))
        {
        }
        
        public EmberFlexberryDummy.Vote this[int index]
        {
            get
            {
                return ((EmberFlexberryDummy.Vote)(this.ItemByIndex(index)));
            }
        }
        
        public virtual void Add(EmberFlexberryDummy.Vote dataobject)
        {
            this.AddObject(((ICSSoft.STORMNET.DataObject)(dataobject)));
        }
    }
}
