//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmberFlexberryDummy
{
    using System;
    using System.Xml;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Vote type.
    /// </summary>
    // *** Start programmer edit section *** (VoteType CustomAttributes)

    // *** End programmer edit section *** (VoteType CustomAttributes)
    public enum VoteType
    {
        
        // *** Start programmer edit section *** (VoteType.Like CustomAttributes)

        // *** End programmer edit section *** (VoteType.Like CustomAttributes)
        Like,
        
        // *** Start programmer edit section *** (VoteType.Dislike CustomAttributes)

        // *** End programmer edit section *** (VoteType.Dislike CustomAttributes)
        Dislike,
    }
}
